In [1]:
import numpy as np
import pandas as pd
import re
pd.set_option('display.max_columns', None)

import warnings as wr
wr.filterwarnings('ignore')

In [2]:
df = pd.read_csv('data/03_flats_cleaned.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2904 entries, 0 to 2903
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bedroom         2904 non-null   int64
 2   bathroom        2904 non-null   int64
 3   balcony         2904 non-null   int64
 4   addl_room       2904 non-null   int64
 5   floor_rise      2904 non-null   object
 6   area_sqm        2904 non-null   float64
 7   area_type       2904 non-null   object
 8   age             2904 non-null   object
 9   society         2904 non-null   object
 10  locality        2904 non-null   object
 11  furnishDetails  2147 non-null   object
 12  nearby_loc      2904 non-null   object
dtypes: float64(2), int64(4), object(7)
memory usage: 295.1+ KB

In [4]:
df.head(4)

,price_cr,bedroom,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,locality,furnishDetails,nearby_loc
0,0.45,2,2,1,0,mid,83.61,carpet,new,maa bhagwati residency,krishna colony,"['3 fan', '4 light', '1 wardrobe', 'no ac', 'n...","['chintapurni mandir', 'state bank atm', 'pear..."
1,0.50,2,2,1,0,low,60.39,carpet,old,apna enclave,ashok vihar,"['3 wardrobe', '4 fan', '1 exhaust fan', '1 ge...","['chintapurni mandir', 'sheetla mata mandir', ..."
2,0.40,2,2,3,0,high,55.28,carpet,new,tulsiani easy in homes,sohna,NaN,"['huda city metro', 'golf course extn road', '..."
3,1.47,2,2,2,1,low,111.48,carpet,mid aged,smart world orchard,sector 61 gurgaon,NaN,"['sector 55-56 metro station', 'bestech centra..."

In [5]:
df['locality'].unique()

array(['krishna colony', 'ashok vihar', 'sohna', 'sector 61 gurgaon',
       'sector 92 gurgaon', 'dwarka expressway gurgaon',
       'sector 104 gurgaon', 'sector 88b gurgaon', 'sector 78 gurgaon',
       'sector 81 gurgaon', 'sector 79 gurgaon', 'sector 90 gurgaon',
       'sector 108 gurgaon', 'sector 62 gurgaon', 'sector 102 gurgaon',
       'sector-33 sohna', 'sector 89 gurgaon', 'sector 113 gurgaon',
       'sector 65 gurgaon', 'sector 48 gurgaon', 'sector 37c gurgaon',
       'sector 3 gurgaon', 'new palam vihar', 'sector 43 gurgaon',
       'sector 88a gurgaon', 'sector 68 gurgaon', 'sector 109 gurgaon',
       'sector 106 gurgaon', 'sector 82 gurgaon',
       'ashok vihar phase 3 extension', 'sector 85 gurgaon',
       'sector 82a gurgaon', 'dlf phase 4', 'sector 10a gurgaon',
       'sector 1a imt manesar', 'block a surya vihar',
       'sector 84 gurgaon', 'sector 33 gurgaon', 'sector 71 gurgaon',
       'sector-7 housing board', 'sector 77 gurgaon',
       'sector 37d gurgaon', 'sector 67a gurgaon', 'sector 57 gurgaon',
       'sector 95 gurgaon', 'sector 99a gurgaon', 'sector 103 gurgaon',
       'sector 49 gurgaon', 'sector 30 gurgaon', 'sector 86 gurgaon',
       'sector 66 gurgaon', 'sector 15 part 1', 'laxman vihar',
       'sector 22 gurgaon', 'sector 63a gurgaon', 'sector 95a gurgaon',
       'sector 52 gurgaon', 'sector 67 gurgaon', 'sushant lok phase 1',
       'sector 107 gurgaon', 'sector 12a gurgaon', 'sohna road',
       'ashok vihar phase 2', 'rajiv colony', 'garauli kalan',
       'bhawani enclave', 'sector 99 gurgaon', 'iffco chowk',
       'palam vihar', 'sector 91 gurgaon', 'near sector 1 market',
       'sector 70 gurgaon', 'sector 70a gurgaon', 'gwal pahari',
       'sector 7 gurgaon', 'malibu town', 'golf course road',
       'sector 4 gurgaon', 'sector 54 gurgaon', 'sector 111 gurgaon',
       'chakkarpur', 'sector 41 gurgaon', 'sector 12 gurgaon',
       'sector 73 gurgaon', 'sector 36 sohna', 'sector 56 gurgaon',
       'sector 83 gurgaon', 'sector 53 gurgaon', 'sector 72 gurgaon',
       'sector 1 imt manesar', 'sector 69 gurgaon', 'sector 47 gurgaon',
       'sector 63 gurgaon', 'sector 110 gurgaon', 'kanahi', 'dlf phase 5',
       'sector 9a gurgaon', 'sector 28 gurgaon', 'sector 14 gurgaon',
       'nirvana country', 'dlf phase 2', 'sector 59 gurgaon',
       'dlf phase 3', 'heritage city', 'sector 1 gurgaon',
       'sector 38 gurgaon', 'sector 15 gurgaon', 'ambience island',
       'sector 112 gurgaon', 'sector 45 gurgaon', 'sector 74 gurgaon',
       'sector 60 gurgaon', 'sector 2 gurgaon', 'sector 51 gurgaon',
       'sector 50 gurgaon', 'suncity', 'sector 110 a gurgaon',
       'sector 39 gurgaon', 'sai kunj', 'manesar', 'sector 58 gurgaon',
       'imt manesar', 'sector 80 gurgaon', 'mg road', 'sector 55 gurgaon',
       'sultanpur', 'sector 93 gurgaon', 'sector 23a gurgaon',
       'sector 36a gurgaon', 'civil lines', 'sector 76 gurgaon',
       'new colony, sector 7', 'sector 31 gurgaon', 'lajpat nagar',
       'sector 89 a gurgaon', 'new gurgaon', 'surya vihar',
       'near pataudi chowk', 'cyber city', 'new colony', 'subhash nagar',
       'ats marigold', 'sector-2 sohna', 'adarsh nagar',
       'sector 37a gurgaon', 'sushant lok phase 3', 'carterpuri village',
       'valley view estate', 'shanti nagar', 'sushant lok',
       'mehrauli gurgaon road', 'laxman vihar phase 2',
       'gurgaon faridabad road', 'sector 36 gurgaon',
       'old delhi road, opp sector-14', 'sector 21 gurgaon',
       'sector 5 gurgaon', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'sector 24 gurgaon',
       'palam vihar extension', 'saroop garden rajendra park',
       'sector 4 urban estate', 'bptp', 'sector 105 gurgaon',
       'south city 1', 'sector 9 gurgaon', 'sector 40 gurgaon',
       'dharam colony', 'rajendra park',
       'godrej aria , sector 79 , gurgaon'], dtype=object)

In [6]:
df['city'] = np.where(df['locality'].str.contains('imt|manesar'), 'manesar',
                     np.where(df['locality'].str.contains('sohna'), 'sohna', 'gurgaon'))

In [7]:
df['city'].unique()

array(['gurgaon', 'sohna', 'manesar'], dtype=object)

In [8]:
#localities with sector not mentioned

In [9]:
df[~df['locality'].str.contains('sector')]['locality'].unique()

array(['krishna colony', 'ashok vihar', 'sohna',
       'dwarka expressway gurgaon', 'new palam vihar',
       'ashok vihar phase 3 extension', 'dlf phase 4',
       'block a surya vihar', 'laxman vihar', 'sushant lok phase 1',
       'sohna road', 'ashok vihar phase 2', 'rajiv colony',
       'garauli kalan', 'bhawani enclave', 'iffco chowk', 'palam vihar',
       'gwal pahari', 'malibu town', 'golf course road', 'chakkarpur',
       'kanahi', 'dlf phase 5', 'nirvana country', 'dlf phase 2',
       'dlf phase 3', 'heritage city', 'ambience island', 'suncity',
       'sai kunj', 'manesar', 'imt manesar', 'mg road', 'sultanpur',
       'civil lines', 'lajpat nagar', 'new gurgaon', 'surya vihar',
       'near pataudi chowk', 'cyber city', 'new colony', 'subhash nagar',
       'ats marigold', 'adarsh nagar', 'sushant lok phase 3',
       'carterpuri village', 'valley view estate', 'shanti nagar',
       'sushant lok', 'mehrauli gurgaon road', 'laxman vihar phase 2',
       'gurgaon faridabad road', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'palam vihar extension',
       'saroop garden rajendra park', 'bptp', 'south city 1',
       'dharam colony', 'rajendra park'], dtype=object)

In [10]:
#changing these localities to their respective sectors

In [11]:
df['locality'] = df['locality'].str.replace('krishna colony','sector 7')
df['locality'] = df['locality'].str.replace('ashok vihar','sector 3')
df['locality'] = df['locality'].str.replace('sohna','sector 33')
df['locality'] = df['locality'].str.replace('dwarka expressway gurgaon','sector 102')
df['locality'] = df['locality'].str.replace('new palam vihar','sector 110')
df['locality'] = df['locality'].str.replace('ashok vihar phase 3 extension','sector 3')
df['locality'] = df['locality'].str.replace('dlf phase 4','sector 28')
df['locality'] = df['locality'].str.replace('block a surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('laxman vihar','sector 4')
df['locality'] = df['locality'].str.replace('sushant lok phase 1','sector 43')
df['locality'] = df['locality'].str.replace('sohna road','sector 48')
df['locality'] = df['locality'].str.replace('ashok vihar phase 2','sector 5')

In [12]:
df['locality'] = df['locality'].str.replace('rajiv colony','sector 33')
df['locality'] = df['locality'].str.replace('garauli kalan','sector 37')
df['locality'] = df['locality'].str.replace('bhawani enclave','sector 9')
df['locality'] = df['locality'].str.replace('iffco chowk','sector 17')
df['locality'] = df['locality'].str.replace('palam vihar','sector 2')
df['locality'] = df['locality'].str.replace('gwal pahari','sector 2')
df['locality'] = df['locality'].str.replace('malibu town','sector 47')
df['locality'] = df['locality'].str.replace('golf course road','sector 54')
df['locality'] = df['locality'].str.replace('chakkarpur','sector 28')
df['locality'] = df['locality'].str.replace('kanahi','sector 45')
df['locality'] = df['locality'].str.replace('dlf phase 5','sector 54')
df['locality'] = df['locality'].str.replace('nirvana country','sector 50')

In [13]:
df['locality'] = df['locality'].str.replace('dlf phase 2','sector 25')
df['locality'] = df['locality'].str.replace('dlf phase 3','sector 24')
df['locality'] = df['locality'].str.replace('heritage city','sector 25')
df['locality'] = df['locality'].str.replace('ambience island','sector 24')
df['locality'] = df['locality'].str.replace('suncity','sector 54')
df['locality'] = df['locality'].str.replace('sai kunj','sector 110')
df['locality'] = df['locality'].str.replace('manesar','sector 1')
df['locality'] = df['locality'].str.replace('imt manesar','sector 1')
df['locality'] = df['locality'].str.replace('mg road','sector 28')
df['locality'] = df['locality'].str.replace('sultanpur','sector 142')
df['locality'] = df['locality'].str.replace('civil lines','sector 15')
df['locality'] = df['locality'].str.replace('lajpat nagar','sector 4')

In [14]:
df['locality'] = df['locality'].str.replace('new gurgaon','sector 82')
df['locality'] = df['locality'].str.replace('surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('near pataudi chowk','sector 10')
df['locality'] = df['locality'].str.replace('cyber city','sector 24')
df['locality'] = df['locality'].str.replace('new colony','sector 7')
df['locality'] = df['locality'].str.replace('subhash nagar','sector 8')
df['locality'] = df['locality'].str.replace('ats marigold','sector 89')
df['locality'] = df['locality'].str.replace('adarsh nagar','sector 12')
df['locality'] = df['locality'].str.replace('sushant lok phase 3','sector 57')
df['locality'] = df['locality'].str.replace('carterpuri village','sector 23')
df['locality'] = df['locality'].str.replace('valley view estate','sector 2')
df['locality'] = df['locality'].str.replace('shanti nagar','sector 11')

In [15]:
df['locality'] = df['locality'].str.replace('sushant lok','sector 43')
df['locality'] = df['locality'].str.replace('mehrauli gurgaon road','sector 28')
df['locality'] = df['locality'].str.replace('laxman vihar phase 2','sector 4')
df['locality'] = df['locality'].str.replace('gurgaon faridabad road','sector 56')
df['locality'] = df['locality'].str.replace('dayanand colony','sector 6')
df['locality'] = df['locality'].str.replace('samaspur','sector 51')
df['locality'] = df['locality'].str.replace('nirvana country pocket h','sector 50')
df['locality'] = df['locality'].str.replace('patel nagar','sector 15')
df['locality'] = df['locality'].str.replace('surat nagar 1','sector 104')
df['locality'] = df['locality'].str.replace('sispal vihar','sector 49')
df['locality'] = df['locality'].str.replace('golf course ext road','sector 65')
df['locality'] = df['locality'].str.replace('shankar vihar','sector 104')

In [16]:
df['locality'] = df['locality'].str.replace('new palam vihar phase 2','sector 110')
df['locality'] = df['locality'].str.replace('palam vihar extension','sector 2')
df['locality'] = df['locality'].str.replace('saroop garden rajendra park','sector 105')
df['locality'] = df['locality'].str.replace('bptp','sector 37')
df['locality'] = df['locality'].str.replace('south city 1','sector 41')
df['locality'] = df['locality'].str.replace('dharam colony','sector 23')
df['locality'] = df['locality'].str.replace('rajendra park','sector 105')

In [17]:
df['sector'] = df['locality'].str.extract(r"(\d+)").astype('float')
df['sector'] = df['sector'].apply(lambda x: 'sector ' + str(int(x)) if not np.isnan(x) else x)

In [18]:
df['sector'].unique()

array(['sector 7', 'sector 3', 'sector 33', 'sector 61', 'sector 92',
       'sector 102', 'sector 104', 'sector 88', 'sector 78', 'sector 81',
       'sector 79', 'sector 90', 'sector 108', 'sector 62', 'sector 89',
       'sector 113', 'sector 65', 'sector 48', 'sector 37', 'sector 110',
       'sector 43', 'sector 68', 'sector 109', 'sector 106', 'sector 82',
       'sector 85', 'sector 28', 'sector 10', 'sector 1', 'sector 21',
       'sector 84', 'sector 71', 'sector 77', 'sector 67', 'sector 57',
       'sector 95', 'sector 99', 'sector 103', 'sector 49', 'sector 30',
       'sector 86', 'sector 66', 'sector 15', 'sector 4', 'sector 22',
       'sector 63', 'sector 52', 'sector 107', 'sector 12', 'sector 9',
       'sector 17', 'sector 2', 'sector 91', 'sector 70', 'sector 47',
       'sector 54', 'sector 111', 'sector 41', 'sector 73', 'sector 36',
       'sector 56', 'sector 83', 'sector 53', 'sector 72', 'sector 69',
       'sector 45', 'sector 14', 'sector 50', 'sector 25', 'sector 59',
       'sector 24', 'sector 38', 'sector 112', 'sector 74', 'sector 60',
       'sector 51', 'sector 39', 'sector 58', 'sector 80', 'sector 55',
       'sector 142', 'sector 93', 'sector 23', 'sector 76', 'sector 31',
       'sector 8', 'sector 11', 'sector 5', 'sector 6', 'sector 105',
       'sector 40'], dtype=object)

In [19]:
df['locality'].unique()

array(['sector 7', 'sector 3', 'sector 33', 'sector 61 gurgaon',
       'sector 92 gurgaon', 'sector 102', 'sector 104 gurgaon',
       'sector 88b gurgaon', 'sector 78 gurgaon', 'sector 81 gurgaon',
       'sector 79 gurgaon', 'sector 90 gurgaon', 'sector 108 gurgaon',
       'sector 62 gurgaon', 'sector 102 gurgaon', 'sector-33 sector 33',
       'sector 89 gurgaon', 'sector 113 gurgaon', 'sector 65 gurgaon',
       'sector 48 gurgaon', 'sector 37c gurgaon', 'sector 3 gurgaon',
       'sector 110', 'sector 43 gurgaon', 'sector 88a gurgaon',
       'sector 68 gurgaon', 'sector 109 gurgaon', 'sector 106 gurgaon',
       'sector 82 gurgaon', 'sector 3 phase 3 extension',
       'sector 85 gurgaon', 'sector 82a gurgaon', 'sector 28',
       'sector 10a gurgaon', 'sector 1a imt sector 1', 'sector 21',
       'sector 84 gurgaon', 'sector 33 gurgaon', 'sector 71 gurgaon',
       'sector-7 housing board', 'sector 77 gurgaon',
       'sector 37d gurgaon', 'sector 67a gurgaon', 'sector 57 gurgaon',
       'sector 95 gurgaon', 'sector 99a gurgaon', 'sector 103 gurgaon',
       'sector 49 gurgaon', 'sector 30 gurgaon', 'sector 86 gurgaon',
       'sector 66 gurgaon', 'sector 15 part 1', 'sector 4',
       'sector 22 gurgaon', 'sector 63a gurgaon', 'sector 95a gurgaon',
       'sector 52 gurgaon', 'sector 67 gurgaon', 'sector 43',
       'sector 107 gurgaon', 'sector 12a gurgaon', 'sector 33 road',
       'sector 3 phase 2', 'sector 37', 'sector 9', 'sector 99 gurgaon',
       'sector 17', 'sector 2', 'sector 91 gurgaon',
       'near sector 1 market', 'sector 70 gurgaon', 'sector 70a gurgaon',
       'sector 7 gurgaon', 'sector 47', 'sector 54', 'sector 4 gurgaon',
       'sector 54 gurgaon', 'sector 111 gurgaon', 'sector 41 gurgaon',
       'sector 12 gurgaon', 'sector 73 gurgaon', 'sector 36 sector 33',
       'sector 56 gurgaon', 'sector 83 gurgaon', 'sector 53 gurgaon',
       'sector 72 gurgaon', 'sector 1 imt sector 1', 'sector 69 gurgaon',
       'sector 47 gurgaon', 'sector 63 gurgaon', 'sector 110 gurgaon',
       'sector 45', 'sector 9a gurgaon', 'sector 28 gurgaon',
       'sector 14 gurgaon', 'sector 50', 'sector 25', 'sector 59 gurgaon',
       'sector 24', 'sector 1 gurgaon', 'sector 38 gurgaon',
       'sector 15 gurgaon', 'sector 112 gurgaon', 'sector 45 gurgaon',
       'sector 74 gurgaon', 'sector 60 gurgaon', 'sector 2 gurgaon',
       'sector 51 gurgaon', 'sector 50 gurgaon', 'sector 110 a gurgaon',
       'sector 39 gurgaon', 'sector 1', 'sector 58 gurgaon',
       'imt sector 1', 'sector 80 gurgaon', 'sector 55 gurgaon',
       'sector 142', 'sector 93 gurgaon', 'sector 23a gurgaon',
       'sector 36a gurgaon', 'sector 15', 'sector 76 gurgaon',
       'sector 7, sector 7', 'sector 31 gurgaon', 'sector 89 a gurgaon',
       'sector 82', 'sector 10', 'sector 8', 'sector 89',
       'sector-2 sector 33', 'sector 12', 'sector 37a gurgaon',
       'sector 57', 'sector 23', 'sector 11', 'sector 4 phase 2',
       'sector 56', 'sector 36 gurgaon', 'old delhi road, opp sector-14',
       'sector 21 gurgaon', 'sector 5 gurgaon', 'sector 6', 'sector 51',
       'sector 50 pocket h', 'sector 104', 'sector 49', 'sector 65',
       'sector 110 phase 2', 'sector 24 gurgaon', 'sector 2 extension',
       'sector 105', 'sector 4 urban estate', 'sector 105 gurgaon',
       'sector 41', 'sector 9 gurgaon', 'sector 40 gurgaon',
       'godrej aria , sector 79 , gurgaon'], dtype=object)

In [20]:
df.drop(columns=['locality'], inplace=True)

In [21]:
df.sample(4)

,price_cr,bedroom,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector
595,2.35,3,4,3,1,mid,247.12,super built up,new,bestech park view grand spa,"['5 wardrobe', '7 fan', '1 exhaust fan', '20 l...","['sapphire 83 mall', 'nh-8, imt manesar', 'dwa...",gurgaon,sector 81
1950,0.96,2,2,3,1,high,135.36,super built up,mid aged,eldeco accolade,[],"['global city centre', 'sohna road', 'damdama ...",sohna,sector 33
147,0.45,2,2,1,0,low,58.16,carpet,new,green court,"['1 wardrobe', '3 fan', '1 exhaust fan', '6 li...","['baba kanala chowk', 'pataudi rd', 'gurukul p...",gurgaon,sector 90
962,1.05,3,3,2,1,high,163.04,super built up,new,vatika lifestyle homes,"['4 wardrobe', '6 fan', '1 exhaust fan', '2 ge...","['sapphire 83 mall', 'nh – 08', 'knowledge tre...",gurgaon,sector 83

In [22]:
# handling nearby_loc feature
import ast

df['nearby_1'] = df['nearby_loc'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

df['landmark_count'] = df['nearby_1'].apply(lambda x: len(x))

In [23]:
from collections import Counter

stopwords = {'the', 'a', 'an', 'and', 'of', 'in', 'at', 'to', 'is', 'for', 'on'}

all_words = []
for landmark_list in df['nearby_1']:
    for landmark in landmark_list:
        # Lowercase, remove special characters, split into words
        words = re.sub(r'[^a-z0-9\s]', '', landmark.lower()).split()
        filtered = [w for w in words if w not in stopwords and len(w) > 2]
        all_words.extend(filtered)

word_freq = Counter(all_words)

In [24]:
top_n = 100
nearby_freq = pd.DataFrame(word_freq.most_common(top_n), columns=['word', 'frequency'])

In [25]:
not_landmark = ('gurgaon','sector','gandhi','indira','dwarka','gurugram','sohna',
                'igi','delhi','manesar','imt','5556','sec')

general_landmarks = nearby_freq[~nearby_freq['word'].isin(not_landmark)].iloc[:,0].tolist()

In [26]:
df.sample(4)

,price_cr,bedroom,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector,nearby_1,landmark_count
1703,1.66,3,3,2,0,high,152.18,super built up,new,tulip violet,"['1 modular kitchen', 'no ac', 'no bed', 'no c...","['airia mall sector 68', 'southern peripheral ...",gurgaon,sector 69,"[airia mall sector 68, southern peripheral roa...",10
2678,1.50,4,3,3,0,high,153.29,carpet,new,oriental valley chs,"['6 fan', '1 exhaust fan', '3 geyser', '12 lig...","['chintapurni mandir', 'state bank atm', 'esic...",gurgaon,sector 9,"[chintapurni mandir, state bank atm, esic hosp...",50
384,1.75,3,4,3,1,high,223.71,super built up,new,ss the leaf,"['5 ac', 'no bed', 'no chimney', 'no curtains'...","['sapphire 83 mall', 'dwarka expressway', 'cen...",gurgaon,sector 85,"[sapphire 83 mall, dwarka expressway, central ...",13
318,1.30,4,6,2,1,high,258.83,super built up,new,ansal heights 86,NaN,"['iris broadway mall', 'delhi jaipur expresswa...",gurgaon,sector 86,"[iris broadway mall, delhi jaipur expressway, ...",4

In [27]:
landmark_dict = {
    'has_hospital_or_clinic': ['hospital','nursing','clinic','health care'],
    'has_police_stn': ['police'],
    'has_fire_stn': ['fire'],
    'has_mall': ['mall'],
    'has_market': ['pharmacy','market'],
    'has_park': ['park'],
    'has_bank_or_atm': ['atm','bank'],
    'has_institute': ['institute','school','vidyalaya','college','university','academy'],
    'has_airport': ['airport'],
    'has_rly_stn': ['railway station','rly station','railway stn','rly stn'],
    'has_metro_stn': ['metro'],
    'has_expy': ['expressway','expy'],
    'has_petrol_pump': ['petrol','cng','oil','petroleum'],
    'has_hotel': ['hotel','inn','radisson','lemontree'],
    'has_temple_or_church': ['temple','mandir','church'],
    'has_famous_chowk': ['chowk'],
    'has_club': ['club'],
    'has_stadium': ['stadium'],
    'has_restro_cafe': ['restaurant','cafe','food court','dhaba','burger','pizza','dominos','mcdonald','coffee']
}

In [28]:
for key, values in landmark_dict.items():
    df[key] = 0
    for index, df_nearby in df.iterrows():
        landmarks = df_nearby['nearby_loc'].replace("[",'').replace("]",'').replace("'",'').split(",")
        landmarks = [landmark.strip() for landmark in landmarks if len(landmark.strip())>2]
        for landmark in landmarks:
            for val in values:
                if val in landmark:
                    df.loc[index,key] = 1
                    break

In [29]:
df.sample(4)

,price_cr,bedroom,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector,nearby_1,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe
824,2.40,3,4,3,1,high,195.38,super built up,new,dlf the ultima,"['1 fridge', '1 fan', '1 exhaust fan', '1 dini...","['huda metro station (gurugram)', 'vatika town...",gurgaon,sector 81,"[huda metro station (gurugram), vatika town sq...",9,1,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0
666,0.98,2,3,3,1,mid,119.19,super built up,new,experion the heartsong,"['1 bed', '1 sofa', '8 light', '3 ac', '1 curt...","['galleria 108 mall', 'dwarka expressway', 'ce...",gurgaon,sector 108,"[galleria 108 mall, dwarka expressway, central...",9,1,0,0,1,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0
1880,0.72,2,2,1,0,mid,84.17,carpet,new,orchid island,[],"['rapid metro sector 55-56', 'tigra market', '...",gurgaon,sector 51,"[rapid metro sector 55-56, tigra market, garim...",9,1,0,0,0,1,1,0,1,1,0,1,0,0,0,1,0,0,0,0
358,1.28,3,3,3,0,low,124.49,carpet,new,suncity vatsal valley,"['3 wardrobe', '1 water purifier', '5 fan', '1...","['sector 55-56 metro station', 'banjara market...",gurgaon,sector 2,"[sector 55-56 metro station, banjara market gu...",11,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0

In [30]:
for row in df['furnishDetails']:
    row = str(row).lower().replace('[','').replace(']','').replace("'","").replace('no','0').strip().split(",")
    for item in row:
        if item != 'nan':
            name_obj = re.findall(r"([a-zA-Z/s]+)", item)
            if name_obj is not None:
                name = " ".join(name_obj)
                
                count_obj = re.search(r"(\d+)", item)
                if count_obj is not None:
                    count = count_obj.group()
                    df[name]=count
                else:
                    df[name]=0

df.drop(columns=['nearby_1','nearby_loc','furnishDetails'], inplace=True)

In [31]:
df['fan'].unique()

array(['6'], dtype=object)

In [32]:
df.sample(4)

,price_cr,bedroom,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,city,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,
1008,2.65,4,4,3,1,high,238.48,super built up,old,bestech park view city,gurgaon,sector 48,15,1,1,0,1,0,1,1,1,1,0,1,0,1,0,1,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,0
2700,0.78,2,2,2,0,high,126.35,built up,new,ansal heights 86,gurgaon,sector 86,4,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,0
1584,2.00,4,5,3,1,mid,222.97,super built up,old,tulip ivory,gurgaon,sector 70,10,1,0,0,1,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,0
1957,0.40,2,2,2,0,high,83.61,super built up,new,pivotal riddhi siddhi,gurgaon,sector 99,8,0,0,0,1,0,0,0,1,1,0,1,1,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2904 entries, 0 to 2903
Data columns (total 51 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   price_cr                2904 non-null   float64
 1   bedroom                 2904 non-null   int64
 2   bathroom                2904 non-null   int64
 3   balcony                 2904 non-null   int64
 4   addl_room               2904 non-null   int64
 5   floor_rise              2904 non-null   object
 6   area_sqm                2904 non-null   float64
 7   area_type               2904 non-null   object
 8   age                     2904 non-null   object
 9   society                 2904 non-null   object
 10  city                    2904 non-null   object
 11  sector                  2904 non-null   object
 12  landmark_count          2904 non-null   int64
 13  has_hospital_or_clinic  2904 non-null   int64
 14  has_police_stn          2904 non-null   int64
 15  has_fire_stn            2904 non-null   int64
 16  has_mall                2904 non-null   int64
 17  has_market              2904 non-null   int64
 18  has_park                2904 non-null   int64
 19  has_bank_or_atm         2904 non-null   int64
 20  has_institute           2904 non-null   int64
 21  has_airport             2904 non-null   int64
 22  has_rly_stn             2904 non-null   int64
 23  has_metro_stn           2904 non-null   int64
 24  has_expy                2904 non-null   int64
 25  has_petrol_pump         2904 non-null   int64
 26  has_hotel               2904 non-null   int64
 27  has_temple_or_church    2904 non-null   int64
 28  has_famous_chowk        2904 non-null   int64
 29  has_club                2904 non-null   int64
 30  has_stadium             2904 non-null   int64
 31  has_restro_cafe         2904 non-null   int64
 32  fan                     2904 non-null   object
 33  light                   2904 non-null   object
 34  wardrobe                2904 non-null   object
 35  ac                      2904 non-null   object
 36  bed                     2904 non-null   object
 37  chimney                 2904 non-null   object
 38  curtains                2904 non-null   object
 39  dining table            2904 non-null   object
 40  exhaust fan             2904 non-null   object
 41  geyser                  2904 non-null   object
 42  modular kitchen         2904 non-null   object
 43  microwave               2904 non-null   object
 44  fridge                  2904 non-null   object
 45  sofa                    2904 non-null   object
 46  stove                   2904 non-null   object
 47  tv                      2904 non-null   object
 48  washing machine         2904 non-null   object
 49  water purifier          2904 non-null   object
 50                          2904 non-null   int64
dtypes: float64(2), int64(25), object(24)
memory usage: 1.1+ MB

In [34]:
df.columns

Index(['price_cr', 'bedroom', 'bathroom', 'balcony', 'addl_room', 'floor_rise',
       'area_sqm', 'area_type', 'age', 'society', 'city', 'sector',
       'landmark_count', 'has_hospital_or_clinic', 'has_police_stn',
       'has_fire_stn', 'has_mall', 'has_market', 'has_park', 'has_bank_or_atm',
       'has_institute', 'has_airport', 'has_rly_stn', 'has_metro_stn',
       'has_expy', 'has_petrol_pump', 'has_hotel', 'has_temple_or_church',
       'has_famous_chowk', 'has_club', 'has_stadium', 'has_restro_cafe', 'fan',
       'light', 'wardrobe', 'ac', 'bed', 'chimney', 'curtains', 'dining table',
       'exhaust fan', 'geyser', 'modular kitchen', 'microwave', 'fridge',
       'sofa', 'stove', 'tv', 'washing machine', 'water purifier', ''],
      dtype='object')

In [35]:
int_cols = ['bedroom','bathroom','balcony','addl_room','landmark_count',
            'has_hospital_or_clinic','has_police_stn','has_fire_stn','has_mall',
            'has_market','has_park','has_bank_or_atm','has_institute','has_airport',
            'has_rly_stn','has_metro_stn','has_expy','has_petrol_pump','has_hotel',
            'has_temple_or_church','has_famous_chowk','has_club','has_stadium',
            'has_restro_cafe','fan','light','wardrobe','ac','bed','chimney',
            'curtains','dining table','exhaust fan','geyser','modular kitchen',
            'microwave','fridge','sofa','stove','tv','washing machine','water purifier']

for col in int_cols:
    df[col] = df[col].astype('float', errors='ignore')

In [36]:
df = df.reindex(columns=['area_sqm','bedroom','bathroom','balcony','addl_room','sector',
                         'landmark_count','has_hospital_or_clinic','has_police_stn','has_fire_stn',
                         'has_mall','has_market','has_park','has_bank_or_atm','has_institute',
                         'has_airport','has_rly_stn','has_metro_stn','has_expy','has_petrol_pump',
                         'has_hotel','has_temple_or_church','has_famous_chowk','has_club','has_stadium',
                         'has_restro_cafe','fan','light','wardrobe','ac','bed','chimney','curtains',
                         'dining table','exhaust fan','geyser','modular kitchen','microwave','fridge',
                         'sofa','stove','tv','washing machine','water purifier','area_type','floor_rise',
                         'age','society','city','price_cr'])

In [37]:
df.sample(3)

,area_sqm,bedroom,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,area_type,floor_rise,age,society,city,price_cr
183,122.63,2.0,2.0,3.0,1.0,sector 92,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,super built up,high,under construction,ansal heights,gurgaon,0.6
977,171.87,3.0,3.0,3.0,1.0,sector 83,10.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,super built up,mid,new,emaar palm gardens,gurgaon,1.6
2333,212.66,3.0,4.0,3.0,1.0,sector 79,11.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,super built up,mid,new,godrej aria,gurgaon,1.7

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2904 entries, 0 to 2903
Data columns (total 50 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   area_sqm                2904 non-null   float64
 1   bedroom                 2904 non-null   float64
 2   bathroom                2904 non-null   float64
 3   balcony                 2904 non-null   float64
 4   addl_room               2904 non-null   float64
 5   sector                  2904 non-null   object
 6   landmark_count          2904 non-null   float64
 7   has_hospital_or_clinic  2904 non-null   float64
 8   has_police_stn          2904 non-null   float64
 9   has_fire_stn            2904 non-null   float64
 10  has_mall                2904 non-null   float64
 11  has_market              2904 non-null   float64
 12  has_park                2904 non-null   float64
 13  has_bank_or_atm         2904 non-null   float64
 14  has_institute           2904 non-null   float64
 15  has_airport             2904 non-null   float64
 16  has_rly_stn             2904 non-null   float64
 17  has_metro_stn           2904 non-null   float64
 18  has_expy                2904 non-null   float64
 19  has_petrol_pump         2904 non-null   float64
 20  has_hotel               2904 non-null   float64
 21  has_temple_or_church    2904 non-null   float64
 22  has_famous_chowk        2904 non-null   float64
 23  has_club                2904 non-null   float64
 24  has_stadium             2904 non-null   float64
 25  has_restro_cafe         2904 non-null   float64
 26  fan                     2904 non-null   float64
 27  light                   2904 non-null   float64
 28  wardrobe                2904 non-null   float64
 29  ac                      2904 non-null   float64
 30  bed                     2904 non-null   float64
 31  chimney                 2904 non-null   float64
 32  curtains                2904 non-null   float64
 33  dining table            2904 non-null   float64
 34  exhaust fan             2904 non-null   float64
 35  geyser                  2904 non-null   float64
 36  modular kitchen         2904 non-null   float64
 37  microwave               2904 non-null   float64
 38  fridge                  2904 non-null   float64
 39  sofa                    2904 non-null   float64
 40  stove                   2904 non-null   float64
 41  tv                      2904 non-null   float64
 42  washing machine         2904 non-null   float64
 43  water purifier          2904 non-null   float64
 44  area_type               2904 non-null   object
 45  floor_rise              2904 non-null   object
 46  age                     2904 non-null   object
 47  society                 2904 non-null   object
 48  city                    2904 non-null   object
 49  price_cr                2904 non-null   float64
dtypes: float64(44), object(6)
memory usage: 1.1+ MB

In [39]:
df.dropna()

,area_sqm,bedroom,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,area_type,floor_rise,age,society,city,price_cr
0,83.61,2.0,2.0,1.0,0.0,sector 7,50.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,carpet,mid,new,maa bhagwati residency,gurgaon,0.45
1,60.39,2.0,2.0,1.0,0.0,sector 3,48.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,carpet,low,old,apna enclave,gurgaon,0.50
2,55.28,2.0,2.0,3.0,0.0,sector 33,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,carpet,high,new,tulsiani easy in homes,sohna,0.40
3,111.48,2.0,2.0,2.0,1.0,sector 61,9.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,carpet,low,mid aged,smart world orchard,gurgaon,1.47
4,124.95,2.0,2.0,3.0,1.0,sector 92,11.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,super built up,mid,under construction,parkwood westend,gurgaon,0.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2899,103.03,2.0,2.0,2.0,0.0,sector 28,45.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,built up,low,old,dlf regency park 1,gurgaon,1.35
2900,176.05,3.0,3.0,3.0,1.0,sector 86,4.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,super built up,high,under construction,ansal heights 86,gurgaon,1.05
2901,362.79,5.0,5.0,3.0,1.0,sector 48,45.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,super built up,mid,old,parsvnath green ville,gurgaon,3.30
2902,343.74,3.0,4.0,3.0,1.0,sector 24,42.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,built up,high,old,ambience lagoon,gurgaon,5.80
2903,290.14,4.0,6.0,3.0,1.0,sector 54,13.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,super built up,mid,new,dlf the crest,gurgaon,11.00

In [40]:
df.to_csv('data/05_flats_FeatureEngineered.csv', index=False)