In [1]:
import numpy as np
import pandas as pd
import re
pd.set_option('display.max_columns', None)

import warnings as wr
wr.filterwarnings('ignore')

In [2]:
df = pd.read_csv('data/03_flats_cleaned.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2904 entries, 0 to 2903
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bhk             2904 non-null   int64
 2   bathroom        2904 non-null   int64
 3   balcony         2904 non-null   int64
 4   addl_room       2904 non-null   int64
 5   floor_rise      2904 non-null   str
 6   area_sqm        2904 non-null   float64
 7   area_type       2904 non-null   str
 8   age             2904 non-null   str
 9   society         2904 non-null   str
 10  locality        2904 non-null   str
 11  furnishDetails  2147 non-null   str
 12  nearby_loc      2904 non-null   str
dtypes: float64(2), int64(4), str(7)
memory usage: 295.1 KB

In [4]:
df.head(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,locality,furnishDetails,nearby_loc
0,0.45,2,2,1,0,mid,83.61,Carpet,new,maa bhagwati residency,Krishna Colony,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Chintapurni Mandir', 'State bank ATM', 'Pear..."
1,0.50,2,2,1,0,low,60.39,Carpet,old,Apna Enclave,Ashok Vihar,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Chintapurni Mandir', 'Sheetla Mata Mandir', ..."
2,0.40,2,2,3,0,high,55.28,Carpet,new,Tulsiani Easy in Homes,Sohna,NaN,"['Huda City Metro', 'Golf Course extn road', '..."
3,1.47,2,2,2,1,low,111.48,Carpet,mid aged,Smart World Orchard,Sector 61 Gurgaon,NaN,"['Sector 55-56 Metro station', 'Bestech Centra..."

In [5]:
df['locality'].unique()

<StringArray>
[                   'Krishna Colony',                       'Ashok Vihar',
                             'Sohna',                 'Sector 61 Gurgaon',
                 'Sector 92 Gurgaon',         'Dwarka Expressway Gurgaon',
                'Sector 104 Gurgaon',                'Sector 88B Gurgaon',
                 'Sector 78 Gurgaon',                 'Sector 81 Gurgaon',
 ...
       'saroop garden rajendra park',             'Sector 4 Urban Estate',
                              'BPTP',                'Sector 105 Gurgaon',
                      'South City 1',                  'Sector 9 Gurgaon',
                 'Sector 40 Gurgaon',                     'Dharam Colony',
                     'Rajendra Park', 'Godrej Aria , sector 79 , Gurgaon']
Length: 178, dtype: str

In [6]:
df['city'] = np.where(df['locality'].str.contains('imt|manesar'), 'manesar',
                     np.where(df['locality'].str.contains('sohna'), 'sohna', 'gurgaon'))

In [7]:
df['city'].unique()

<StringArray>
['gurgaon']
Length: 1, dtype: str

In [8]:
#localities with sector not mentioned

In [9]:
df[~df['locality'].str.contains('sector')]['locality'].unique()

<StringArray>
[             'Krishna Colony',                 'Ashok Vihar',
                       'Sohna',           'Sector 61 Gurgaon',
           'Sector 92 Gurgaon',   'Dwarka Expressway Gurgaon',
          'Sector 104 Gurgaon',          'Sector 88B Gurgaon',
           'Sector 78 Gurgaon',           'Sector 81 Gurgaon',
 ...
       'Palam Vihar Extension', 'saroop garden rajendra park',
       'Sector 4 Urban Estate',                        'BPTP',
          'Sector 105 Gurgaon',                'South City 1',
            'Sector 9 Gurgaon',           'Sector 40 Gurgaon',
               'Dharam Colony',               'Rajendra Park']
Length: 174, dtype: str

In [10]:
#changing these localities to their respective sectors

In [11]:
df['locality'] = df['locality'].str.replace('krishna colony','sector 7')
df['locality'] = df['locality'].str.replace('ashok vihar','sector 3')
df['locality'] = df['locality'].str.replace('sohna','sector 33')
df['locality'] = df['locality'].str.replace('dwarka expressway gurgaon','sector 102')
df['locality'] = df['locality'].str.replace('new palam vihar','sector 110')
df['locality'] = df['locality'].str.replace('ashok vihar phase 3 extension','sector 3')
df['locality'] = df['locality'].str.replace('dlf phase 4','sector 28')
df['locality'] = df['locality'].str.replace('block a surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('laxman vihar','sector 4')
df['locality'] = df['locality'].str.replace('sushant lok phase 1','sector 43')
df['locality'] = df['locality'].str.replace('sohna road','sector 48')
df['locality'] = df['locality'].str.replace('ashok vihar phase 2','sector 5')

In [12]:
df['locality'] = df['locality'].str.replace('rajiv colony','sector 33')
df['locality'] = df['locality'].str.replace('garauli kalan','sector 37')
df['locality'] = df['locality'].str.replace('bhawani enclave','sector 9')
df['locality'] = df['locality'].str.replace('iffco chowk','sector 17')
df['locality'] = df['locality'].str.replace('palam vihar','sector 2')
df['locality'] = df['locality'].str.replace('gwal pahari','sector 2')
df['locality'] = df['locality'].str.replace('malibu town','sector 47')
df['locality'] = df['locality'].str.replace('golf course road','sector 54')
df['locality'] = df['locality'].str.replace('chakkarpur','sector 28')
df['locality'] = df['locality'].str.replace('kanahi','sector 45')
df['locality'] = df['locality'].str.replace('dlf phase 5','sector 54')
df['locality'] = df['locality'].str.replace('nirvana country','sector 50')

In [13]:
df['locality'] = df['locality'].str.replace('dlf phase 2','sector 25')
df['locality'] = df['locality'].str.replace('dlf phase 3','sector 24')
df['locality'] = df['locality'].str.replace('heritage city','sector 25')
df['locality'] = df['locality'].str.replace('ambience island','sector 24')
df['locality'] = df['locality'].str.replace('suncity','sector 54')
df['locality'] = df['locality'].str.replace('sai kunj','sector 110')
df['locality'] = df['locality'].str.replace('manesar','sector 1')
df['locality'] = df['locality'].str.replace('imt manesar','sector 1')
df['locality'] = df['locality'].str.replace('mg road','sector 28')
df['locality'] = df['locality'].str.replace('sultanpur','sector 142')
df['locality'] = df['locality'].str.replace('civil lines','sector 15')
df['locality'] = df['locality'].str.replace('lajpat nagar','sector 4')

In [14]:
df['locality'] = df['locality'].str.replace('new gurgaon','sector 82')
df['locality'] = df['locality'].str.replace('surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('near pataudi chowk','sector 10')
df['locality'] = df['locality'].str.replace('cyber city','sector 24')
df['locality'] = df['locality'].str.replace('new colony','sector 7')
df['locality'] = df['locality'].str.replace('subhash nagar','sector 8')
df['locality'] = df['locality'].str.replace('ats marigold','sector 89')
df['locality'] = df['locality'].str.replace('adarsh nagar','sector 12')
df['locality'] = df['locality'].str.replace('sushant lok phase 3','sector 57')
df['locality'] = df['locality'].str.replace('carterpuri village','sector 23')
df['locality'] = df['locality'].str.replace('valley view estate','sector 2')
df['locality'] = df['locality'].str.replace('shanti nagar','sector 11')

In [15]:
df['locality'] = df['locality'].str.replace('sushant lok','sector 43')
df['locality'] = df['locality'].str.replace('mehrauli gurgaon road','sector 28')
df['locality'] = df['locality'].str.replace('laxman vihar phase 2','sector 4')
df['locality'] = df['locality'].str.replace('gurgaon faridabad road','sector 56')
df['locality'] = df['locality'].str.replace('dayanand colony','sector 6')
df['locality'] = df['locality'].str.replace('samaspur','sector 51')
df['locality'] = df['locality'].str.replace('nirvana country pocket h','sector 50')
df['locality'] = df['locality'].str.replace('patel nagar','sector 15')
df['locality'] = df['locality'].str.replace('surat nagar 1','sector 104')
df['locality'] = df['locality'].str.replace('sispal vihar','sector 49')
df['locality'] = df['locality'].str.replace('golf course ext road','sector 65')
df['locality'] = df['locality'].str.replace('shankar vihar','sector 104')

In [16]:
df['locality'] = df['locality'].str.replace('new palam vihar phase 2','sector 110')
df['locality'] = df['locality'].str.replace('palam vihar extension','sector 2')
df['locality'] = df['locality'].str.replace('saroop garden rajendra park','sector 105')
df['locality'] = df['locality'].str.replace('bptp','sector 37')
df['locality'] = df['locality'].str.replace('south city 1','sector 41')
df['locality'] = df['locality'].str.replace('dharam colony','sector 23')
df['locality'] = df['locality'].str.replace('rajendra park','sector 105')

In [17]:
df['sector'] = df['locality'].str.extract(r"(\d+)").astype('float')

In [18]:
df['sector'].unique()

array([ nan,  61.,  92., 104.,  88.,  78.,  81.,  79.,  90., 108.,  62.,
       102.,  33.,  89., 113.,  65.,  48.,  37.,   3.,  43.,  68., 109.,
       106.,  82.,  85.,   4.,  10.,   1.,  84.,  71.,   7.,  77.,  67.,
        57.,  95.,  99., 103.,  49.,  30.,  86.,  66.,  15.,  22.,  63.,
        52., 107.,  12.,   2.,  91.,  70.,  54., 111.,  41.,  73.,  36.,
        56.,  83.,  53.,  72.,  69.,  47., 110.,   5.,   9.,  28.,  14.,
        59.,  38., 112.,  45.,  74.,  60.,  51.,  50.,  39.,  58.,  80.,
        55.,  93.,  23.,  76.,  31.,  21.,  24., 105.,  40.])

In [19]:
df['locality'].unique()

<StringArray>
[                   'Krishna Colony',                       'Ashok Vihar',
                             'Sohna',                 'Sector 61 Gurgaon',
                 'Sector 92 Gurgaon',         'Dwarka Expressway Gurgaon',
                'Sector 104 Gurgaon',                'Sector 88B Gurgaon',
                 'Sector 78 Gurgaon',                 'Sector 81 Gurgaon',
 ...
                        'sector 105',             'Sector 4 Urban Estate',
                              'BPTP',                'Sector 105 Gurgaon',
                      'South City 1',                  'Sector 9 Gurgaon',
                 'Sector 40 Gurgaon',                     'Dharam Colony',
                     'Rajendra Park', 'Godrej Aria , sector 79 , Gurgaon']
Length: 178, dtype: str

In [20]:
df.drop(columns=['locality'], inplace=True)

In [21]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector
2798,1.45,2,2,3,1,high,83.61204,Super Built up,new,Godrej Oasis,"['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Double Infinity market', 'Pataudi road', 'Dw...",gurgaon,88.0
646,2.00,5,4,3,1,high,297.29000,Carpet,old,KW Royal Court,"['1 Water Purifier', '8 Fan', '1 Fridge', '1 E...","['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stat...",gurgaon,39.0
2367,1.82,3,2,2,0,mid,126.26000,Built Up,under construction,MRG Skyline,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Chintapurni Mandir', 'State bank ATM', 'R K ...",gurgaon,106.0
732,3.00,3,3,3,1,mid,223.25000,Super Built up,new,Ireo Skyon,"['4 Wardrobe', '1 Water Purifier', '1 Exhaust ...","['Sector 55-56 Metro', 'Golf Course Extension'...",gurgaon,60.0

In [22]:
# handling nearby_loc feature
import ast

df['nearby_1'] = df['nearby_loc'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

df['landmark_count'] = df['nearby_1'].apply(lambda x: len(x))

In [23]:
from collections import Counter

stopwords = {'the', 'a', 'an', 'and', 'of', 'in', 'at', 'to', 'is', 'for', 'on'}

all_words = []
for landmark_list in df['nearby_1']:
    for landmark in landmark_list:
        # Lowercase, remove special characters, split into words
        words = re.sub(r'[^a-z0-9\s]', '', landmark.lower()).split()
        filtered = [w for w in words if w not in stopwords and len(w) > 2]
        all_words.extend(filtered)

word_freq = Counter(all_words)

In [24]:
top_n = 100
nearby_freq = pd.DataFrame(word_freq.most_common(top_n), columns=['word', 'frequency'])

In [25]:
not_landmark = ('gurgaon','sector','gandhi','indira','dwarka','gurugram','sohna',
                'igi','delhi','manesar','imt','5556','sec')

general_landmarks = nearby_freq[~nearby_freq['word'].isin(not_landmark)].iloc[:,0].tolist()

In [26]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector,nearby_1,landmark_count
46,1.60,2,2,2,0,low,102.19,Carpet,new,DLF Regency Park 1,"['1 Bed', '1 Wardrobe', '1 Fan', '1 Light', '1...","['Sector 42-43 metro station', 'Dlf phase 1 me...",gurgaon,4.0,"[Sector 42-43 metro station, Dlf phase 1 metro...",45
1713,1.54,4,4,3,1,high,219.62,Super Built up,old,DLF New Town Heights 2,NaN,"['City Square', 'Vatika Town Square', 'Bharat ...",gurgaon,86.0,"[City Square, Vatika Town Square, Bharat Ram G...",15
1140,0.28,2,2,2,0,high,45.43,Carpet,new,Signature Global Solera,NaN,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', '...",gurgaon,107.0,"[Gurgaon Dreamz Mall, Dwarka Expressway, s Cen...",10
2731,1.25,3,2,3,1,low,139.35,Carpet,new,Vatika INXT Floors,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Vatika Town Square-INXT', 'NH 48, Sector 78,...",gurgaon,82.0,"[Vatika Town Square-INXT, NH 48, Sector 78, Gu...",6

In [27]:
landmark_dict = {
    'has_hospital_or_clinic': ['hospital','nursing','clinic','health care'],
    'has_police_stn': ['police'],
    'has_fire_stn': ['fire'],
    'has_mall': ['mall'],
    'has_market': ['pharmacy','market'],
    'has_park': ['park'],
    'has_bank_or_atm': ['atm','bank'],
    'has_institute': ['institute','school','vidyalaya','college','university','academy'],
    'has_airport': ['airport'],
    'has_rly_stn': ['railway station','rly station','railway stn','rly stn'],
    'has_metro_stn': ['metro'],
    'has_expy': ['expressway','expy'],
    'has_petrol_pump': ['petrol','cng','oil','petroleum'],
    'has_hotel': ['hotel','inn','radisson','lemontree'],
    'has_temple_or_church': ['temple','mandir','church'],
    'has_famous_chowk': ['chowk'],
    'has_club': ['club'],
    'has_stadium': ['stadium'],
    'has_restro_cafe': ['restaurant','cafe','food court','dhaba','burger','pizza','dominos','mcdonald','coffee']
}

In [28]:
for key, values in landmark_dict.items():
    df[key] = 0
    for index, df_nearby in df.iterrows():
        landmarks = df_nearby['nearby_loc'].replace("[",'').replace("]",'').replace("'",'').split(",")
        landmarks = [landmark.strip() for landmark in landmarks if len(landmark.strip())>2]
        for landmark in landmarks:
            for val in values:
                if val in landmark:
                    df.loc[index,key] += 1
                    break

In [29]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector,nearby_1,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe
74,1.45,3,2,2,0,low,120.77,Built Up,old,AFNHB Jalvayu Vihar,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Icici bank ATM', 'Hdfc ATM', 'Axis bank ATM'...",gurgaon,30.0,"[Icici bank ATM, Hdfc ATM, Axis bank ATM, Citi...",49,0,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,0,2
665,1.48,3,3,3,1,mid,176.52,Super Built up,new,Emaar Palm Gardens,NaN,"['Lante Mall"", ', ', ', ', ', ', ', ', ', ', '...",gurgaon,83.0,"[Lante Mall"", , , , , , , , , , , , , , , , , ...",10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2575,1.40,2,2,2,1,low,114.74,Carpet,mid aged,Signature Global City 63A,[],"['Sector 54 Chowk Metro Station', 'Paras Trini...",gurgaon,63.0,"[Sector 54 Chowk Metro Station, Paras Trinity,...",13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1314,1.10,4,4,3,1,mid,191.10,Carpet,new,Sare Homes,NaN,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",gurgaon,92.0,"[Yadav Clinic, Bangali Clinic, Dr. J. S. Sarka...",8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [30]:
for row in df['furnishDetails']:
    row = str(row).lower().replace('[','').replace(']','').replace("'","").replace('no','0').strip().split(",")
    for item in row:
        if item != 'nan':
            name_obj = re.findall(r"([a-zA-Z/s]+)", item)
            if name_obj is not None:
                name = " ".join(name_obj)
                
                count_obj = re.search(r"(\d+)", item)
                if count_obj is not None:
                    count = count_obj.group()
                    df[name]=count
                else:
                    df[name]=0

df.drop(columns=['nearby_1','nearby_loc','furnishDetails'], inplace=True)

In [31]:
df['fan'].unique()

<StringArray>
['6']
Length: 1, dtype: str

In [32]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,city,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,
1134,1.15,3,3,1,0,mid,170.20,Super Built up,old,Vatika Lifestyle Homes,gurgaon,83.0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,0
1068,1.55,3,3,2,1,high,146.60,Super Built up,new,Tulip Violet,gurgaon,69.0,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,0
1250,3.95,3,4,2,1,high,217.67,Super Built up,new,Sobha City,gurgaon,108.0,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,0
1421,0.73,2,2,3,1,high,117.89,Super Built up,new,Eldeco Accolade,gurgaon,NaN,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,0

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2904 entries, 0 to 2903
Data columns (total 51 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   price_cr                2904 non-null   float64
 1   bhk                     2904 non-null   int64
 2   bathroom                2904 non-null   int64
 3   balcony                 2904 non-null   int64
 4   addl_room               2904 non-null   int64
 5   floor_rise              2904 non-null   str
 6   area_sqm                2904 non-null   float64
 7   area_type               2904 non-null   str
 8   age                     2904 non-null   str
 9   society                 2904 non-null   str
 10  city                    2904 non-null   str
 11  sector                  2581 non-null   float64
 12  landmark_count          2904 non-null   int64
 13  has_hospital_or_clinic  2904 non-null   int64
 14  has_police_stn          2904 non-null   int64
 15  has_fire_stn            2904 non-null   int64
 16  has_mall                2904 non-null   int64
 17  has_market              2904 non-null   int64
 18  has_park                2904 non-null   int64
 19  has_bank_or_atm         2904 non-null   int64
 20  has_institute           2904 non-null   int64
 21  has_airport             2904 non-null   int64
 22  has_rly_stn             2904 non-null   int64
 23  has_metro_stn           2904 non-null   int64
 24  has_expy                2904 non-null   int64
 25  has_petrol_pump         2904 non-null   int64
 26  has_hotel               2904 non-null   int64
 27  has_temple_or_church    2904 non-null   int64
 28  has_famous_chowk        2904 non-null   int64
 29  has_club                2904 non-null   int64
 30  has_stadium             2904 non-null   int64
 31  has_restro_cafe         2904 non-null   int64
 32  fan                     2904 non-null   str
 33  light                   2904 non-null   str
 34  wardrobe                2904 non-null   str
 35  ac                      2904 non-null   str
 36  bed                     2904 non-null   str
 37  chimney                 2904 non-null   str
 38  curtains                2904 non-null   str
 39  dining table            2904 non-null   str
 40  exhaust fan             2904 non-null   str
 41  geyser                  2904 non-null   str
 42  modular kitchen         2904 non-null   str
 43  microwave               2904 non-null   str
 44  fridge                  2904 non-null   str
 45  sofa                    2904 non-null   str
 46  stove                   2904 non-null   str
 47  tv                      2904 non-null   str
 48  washing machine         2904 non-null   str
 49  water purifier          2904 non-null   str
 50                          2904 non-null   int64
dtypes: float64(3), int64(25), str(23)
memory usage: 1.1 MB

In [34]:
df.columns

Index(['price_cr', 'bhk', 'bathroom', 'balcony', 'addl_room', 'floor_rise',
       'area_sqm', 'area_type', 'age', 'society', 'city', 'sector',
       'landmark_count', 'has_hospital_or_clinic', 'has_police_stn',
       'has_fire_stn', 'has_mall', 'has_market', 'has_park', 'has_bank_or_atm',
       'has_institute', 'has_airport', 'has_rly_stn', 'has_metro_stn',
       'has_expy', 'has_petrol_pump', 'has_hotel', 'has_temple_or_church',
       'has_famous_chowk', 'has_club', 'has_stadium', 'has_restro_cafe', 'fan',
       'light', 'wardrobe', 'ac', 'bed', 'chimney', 'curtains', 'dining table',
       'exhaust fan', 'geyser', 'modular kitchen', 'microwave', 'fridge',
       'sofa', 'stove', 'tv', 'washing machine', 'water purifier', ''],
      dtype='str')

In [35]:
int_cols = ['bhk','bathroom','balcony','addl_room','sector','landmark_count',
            'has_hospital_or_clinic','has_police_stn','has_fire_stn','has_mall',
            'has_market','has_park','has_bank_or_atm','has_institute','has_airport',
            'has_rly_stn','has_metro_stn','has_expy','has_petrol_pump','has_hotel',
            'has_temple_or_church','has_famous_chowk','has_club','has_stadium',
            'has_restro_cafe','fan','light','wardrobe','ac','bed','chimney',
            'curtains','dining table','exhaust fan','geyser','modular kitchen',
            'microwave','fridge','sofa','stove','tv','washing machine','water purifier']

for col in int_cols:
    df[col] = df[col].astype('float', errors='ignore')

In [36]:
df = df.reindex(columns=['area_sqm','bhk','bathroom','balcony','addl_room','sector',
                         'landmark_count','has_hospital_or_clinic','has_police_stn','has_fire_stn',
                         'has_mall','has_market','has_park','has_bank_or_atm','has_institute',
                         'has_airport','has_rly_stn','has_metro_stn','has_expy','has_petrol_pump',
                         'has_hotel','has_temple_or_church','has_famous_chowk','has_club','has_stadium',
                         'has_restro_cafe','fan','light','wardrobe','ac','bed','chimney','curtains',
                         'dining table','exhaust fan','geyser','modular kitchen','microwave','fridge',
                         'sofa','stove','tv','washing machine','water purifier','area_type','floor_rise',
                         'age','society','city','price_cr'])

In [37]:
df.sample(3)

,area_sqm,bhk,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,area_type,floor_rise,age,society,city,price_cr
2843,163.51,3.0,4.0,3.0,1.0,106.0,20.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Super Built up,high,under construction,Paras Dews,gurgaon,1.40
50,246.29,4.0,4.0,3.0,0.0,1.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Carpet,mid,old,Deepak Minda,gurgaon,1.25
1501,261.24,4.0,4.0,3.0,1.0,85.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Super Built up,high,new,ss,gurgaon,2.09

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2904 entries, 0 to 2903
Data columns (total 50 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   area_sqm                2904 non-null   float64
 1   bhk                     2904 non-null   float64
 2   bathroom                2904 non-null   float64
 3   balcony                 2904 non-null   float64
 4   addl_room               2904 non-null   float64
 5   sector                  2581 non-null   float64
 6   landmark_count          2904 non-null   float64
 7   has_hospital_or_clinic  2904 non-null   float64
 8   has_police_stn          2904 non-null   float64
 9   has_fire_stn            2904 non-null   float64
 10  has_mall                2904 non-null   float64
 11  has_market              2904 non-null   float64
 12  has_park                2904 non-null   float64
 13  has_bank_or_atm         2904 non-null   float64
 14  has_institute           2904 non-null   float64
 15  has_airport             2904 non-null   float64
 16  has_rly_stn             2904 non-null   float64
 17  has_metro_stn           2904 non-null   float64
 18  has_expy                2904 non-null   float64
 19  has_petrol_pump         2904 non-null   float64
 20  has_hotel               2904 non-null   float64
 21  has_temple_or_church    2904 non-null   float64
 22  has_famous_chowk        2904 non-null   float64
 23  has_club                2904 non-null   float64
 24  has_stadium             2904 non-null   float64
 25  has_restro_cafe         2904 non-null   float64
 26  fan                     2904 non-null   float64
 27  light                   2904 non-null   float64
 28  wardrobe                2904 non-null   float64
 29  ac                      2904 non-null   float64
 30  bed                     2904 non-null   float64
 31  chimney                 2904 non-null   float64
 32  curtains                2904 non-null   float64
 33  dining table            2904 non-null   float64
 34  exhaust fan             2904 non-null   float64
 35  geyser                  2904 non-null   float64
 36  modular kitchen         2904 non-null   float64
 37  microwave               2904 non-null   float64
 38  fridge                  2904 non-null   float64
 39  sofa                    2904 non-null   float64
 40  stove                   2904 non-null   float64
 41  tv                      2904 non-null   float64
 42  washing machine         2904 non-null   float64
 43  water purifier          2904 non-null   float64
 44  area_type               2904 non-null   str
 45  floor_rise              2904 non-null   str
 46  age                     2904 non-null   str
 47  society                 2904 non-null   str
 48  city                    2904 non-null   str
 49  price_cr                2904 non-null   float64
dtypes: float64(45), str(5)
memory usage: 1.1 MB

In [39]:
df.dropna()

,area_sqm,bhk,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,area_type,floor_rise,age,society,city,price_cr
3,111.48,2.0,2.0,2.0,1.0,61.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Carpet,low,mid aged,Smart World Orchard,gurgaon,1.47
4,124.95,2.0,2.0,3.0,1.0,92.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Super Built up,mid,under construction,Parkwood Westend,gurgaon,0.70
6,212.75,3.0,4.0,3.0,0.0,104.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Carpet,high,new,ATS Triumph,gurgaon,1.80
7,125.42,2.0,4.0,3.0,1.0,88.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Built Up,low,under construction,Vatika Xpressions,gurgaon,1.10
8,261.34,3.0,3.0,2.0,1.0,78.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Built Up,high,mid aged,Raheja Revanta,gurgaon,4.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2899,103.03,2.0,2.0,2.0,0.0,4.0,45.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Built Up,low,old,DLF Regency Park 1,gurgaon,1.35
2900,176.05,3.0,3.0,3.0,1.0,86.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Super Built up,high,under construction,Ansal Heights 86,gurgaon,1.05
2901,362.79,5.0,5.0,3.0,1.0,48.0,45.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Super Built up,mid,old,Parsvnath Green Ville,gurgaon,3.30
2902,343.74,3.0,4.0,3.0,1.0,3.0,42.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Built Up,high,old,Ambience Lagoon,gurgaon,5.80
2903,290.14,4.0,6.0,3.0,1.0,54.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,10.0,4.0,6.0,0.0,1.0,0.0,0.0,1.0,5.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,Super Built up,mid,new,DLF The Crest,gurgaon,11.00

In [40]:
df.to_csv('data/05_flats_FeatureEngineered.csv', index=False)