In [1]:
import numpy as np
import pandas as pd
import re
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('03_flats_cleaned.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bhk             2911 non-null   int64
 2   bathroom        2911 non-null   int64
 3   balcony         2911 non-null   int64
 4   addl_room       2911 non-null   int64
 5   floor_rise      2911 non-null   object
 6   area_sqm        2911 non-null   float64
 7   area_type       2911 non-null   object
 8   age             2911 non-null   object
 9   society         2911 non-null   object
 10  locality        2911 non-null   object
 11  furnishDetails  2150 non-null   object
 12  nearby_loc      2911 non-null   object
dtypes: float64(2), int64(4), object(7)
memory usage: 295.8+ KB

In [4]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,locality,furnishDetails,nearby_loc
1579,0.39,2,2,2,0,mid,55.74,carpet,new,signature global synera,sector 81 gurgaon,NaN,"['sapphire 83 mall', 'delhi jaipur expressway'..."
379,1.56,3,4,3,1,high,179.21,super built up,new,dlf the skycourt,sector 86 gurgaon,NaN,"['sapphire 83 mall', 'nh-8, imt manesar', 'rao..."
1904,0.95,3,2,3,0,low,112.41,built up,new,signature global park,sohna,[],"['sector 55-56 metro', 'global city centre', '..."
662,5.90,3,3,3,1,high,312.43,super built up,new,m3m golfestate,sector 65 gurgaon,"['5 fan', '6 light', '5 ac', '1 modular kitche...","['sector 54 chowk metro station', 'sahara mall..."

In [5]:
df['locality'].unique()

array(['krishna colony', 'ashok vihar', 'sohna', 'sector 61 gurgaon',
       'sector 92 gurgaon', 'dwarka expressway gurgaon',
       'sector 104 gurgaon', 'sector 88b gurgaon', 'sector 78 gurgaon',
       'sector 81 gurgaon', 'sector 79 gurgaon', 'sector 90 gurgaon',
       'sector 108 gurgaon', 'sector 62 gurgaon', 'sector 102 gurgaon',
       'sector-33 sohna', 'sector 89 gurgaon', 'sector 113 gurgaon',
       'sector 1 gurgaon', 'sector 65 gurgaon', 'sector 48 gurgaon',
       'sector 37c gurgaon', 'sector 3 gurgaon', 'new palam vihar',
       'sector 43 gurgaon', 'sector 88a gurgaon', 'sector 68 gurgaon',
       'sector 109 gurgaon', 'sector 106 gurgaon', 'sector 82 gurgaon',
       'ashok vihar phase 3 extension', 'sector 85 gurgaon',
       'sector 82a gurgaon', 'dlf phase 4', 'sector 10a gurgaon',
       'sector 1a imt manesar', 'block a surya vihar',
       'sector 84 gurgaon', 'sector 33 gurgaon', 'sector 71 gurgaon',
       'sector-7 housing board', 'sector 77 gurgaon',
       'sector 37d gurgaon', 'sector 67a gurgaon', 'sector 57 gurgaon',
       'sector 95 gurgaon', 'sector 99a gurgaon', 'sector 103 gurgaon',
       'sector 49 gurgaon', 'sector 30 gurgaon', 'sector 86 gurgaon',
       'sector 66 gurgaon', 'sector 15 part 1', 'laxman vihar',
       'sector 22 gurgaon', 'sector 63a gurgaon', 'sector 95a gurgaon',
       'sector 52 gurgaon', 'sector 67 gurgaon', 'sushant lok phase 1',
       'sector 107 gurgaon', 'sector 12a gurgaon', 'sohna road',
       'ashok vihar phase 2', 'rajiv colony', 'garauli kalan',
       'bhawani enclave', 'sector 99 gurgaon', 'iffco chowk',
       'palam vihar', 'sector 91 gurgaon', 'near sector 1 market',
       'sector 70 gurgaon', 'sector 70a gurgaon', 'gwal pahari',
       'sector 7 gurgaon', 'malibu town', 'golf course road',
       'sector 4 gurgaon', 'sector 54 gurgaon', 'sector 111 gurgaon',
       'chakkarpur', 'sector 41 gurgaon', 'sector 12 gurgaon',
       'sector 73 gurgaon', 'sector 36 sohna', 'sector 56 gurgaon',
       'sector 83 gurgaon', 'sector 53 gurgaon', 'sector 72 gurgaon',
       'sector 1 imt manesar', 'sector 69 gurgaon', 'sector 47 gurgaon',
       'sector 63 gurgaon', 'sector 110 gurgaon', 'kanahi', 'dlf phase 5',
       'sector 9a gurgaon', 'sector 28 gurgaon', 'sector 14 gurgaon',
       'nirvana country', 'dlf phase 2', 'sector 59 gurgaon',
       'dlf phase 3', 'heritage city', 'sector 38 gurgaon',
       'sector 15 gurgaon', 'ambience island', 'sector 112 gurgaon',
       'sector 45 gurgaon', 'sector 74 gurgaon', 'sector 60 gurgaon',
       'sector 2 gurgaon', 'sector 51 gurgaon', 'sector 50 gurgaon',
       'suncity', 'sector 110 a gurgaon', 'sector 39 gurgaon', 'sai kunj',
       'manesar', 'sector 58 gurgaon', 'imt manesar', 'sector 80 gurgaon',
       'mg road', 'sector 55 gurgaon', 'sultanpur', 'sector 93 gurgaon',
       'sector 23a gurgaon', 'sector 36a gurgaon', 'civil lines',
       'sector 76 gurgaon', 'new colony, sector 7', 'sector 31 gurgaon',
       'lajpat nagar', 'sector 89 a gurgaon', 'new gurgaon',
       'surya vihar', 'near pataudi chowk', 'cyber city', 'new colony',
       'subhash nagar', 'ats marigold', 'sector-2 sohna', 'adarsh nagar',
       'sector 37a gurgaon', 'sushant lok phase 3', 'carterpuri village',
       'valley view estate', 'shanti nagar', 'sushant lok',
       'mehrauli gurgaon road', 'laxman vihar phase 2',
       'gurgaon faridabad road', 'sector 36 gurgaon',
       'old delhi road, opp sector-14', 'sector 21 gurgaon',
       'sector 5 gurgaon', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'sector 24 gurgaon',
       'palam vihar extension', 'saroop garden rajendra park',
       'sector 4 urban estate', 'bptp', 'sector 105 gurgaon',
       'south city 1', 'sector 9 gurgaon', 'sector 40 gurgaon',
       'dharam colony', 'rajendra park',
       'godrej aria , sector 79 , gurgaon'], dtype=object)

In [6]:
df['city'] = np.where(df['locality'].str.contains('imt|manesar'), 'manesar',
                     np.where(df['locality'].str.contains('sohna'), 'sohna', 'gurgaon'))

In [7]:
df['city'].unique()

array(['gurgaon', 'sohna', 'manesar'], dtype=object)

In [8]:
#localities with sector not mentioned

In [9]:
df[~df['locality'].str.contains('sector')]['locality'].unique()

array(['krishna colony', 'ashok vihar', 'sohna',
       'dwarka expressway gurgaon', 'new palam vihar',
       'ashok vihar phase 3 extension', 'dlf phase 4',
       'block a surya vihar', 'laxman vihar', 'sushant lok phase 1',
       'sohna road', 'ashok vihar phase 2', 'rajiv colony',
       'garauli kalan', 'bhawani enclave', 'iffco chowk', 'palam vihar',
       'gwal pahari', 'malibu town', 'golf course road', 'chakkarpur',
       'kanahi', 'dlf phase 5', 'nirvana country', 'dlf phase 2',
       'dlf phase 3', 'heritage city', 'ambience island', 'suncity',
       'sai kunj', 'manesar', 'imt manesar', 'mg road', 'sultanpur',
       'civil lines', 'lajpat nagar', 'new gurgaon', 'surya vihar',
       'near pataudi chowk', 'cyber city', 'new colony', 'subhash nagar',
       'ats marigold', 'adarsh nagar', 'sushant lok phase 3',
       'carterpuri village', 'valley view estate', 'shanti nagar',
       'sushant lok', 'mehrauli gurgaon road', 'laxman vihar phase 2',
       'gurgaon faridabad road', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'palam vihar extension',
       'saroop garden rajendra park', 'bptp', 'south city 1',
       'dharam colony', 'rajendra park'], dtype=object)

In [10]:
#changing these localities to their respective sectors

In [11]:
df['locality'] = df['locality'].str.replace('krishna colony','sector 7')
df['locality'] = df['locality'].str.replace('ashok vihar','sector 3')
df['locality'] = df['locality'].str.replace('sohna','sector 33')
df['locality'] = df['locality'].str.replace('dwarka expressway gurgaon','sector 102')
df['locality'] = df['locality'].str.replace('new palam vihar','sector 110')
df['locality'] = df['locality'].str.replace('ashok vihar phase 3 extension','sector 3')
df['locality'] = df['locality'].str.replace('dlf phase 4','sector 28')
df['locality'] = df['locality'].str.replace('block a surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('laxman vihar','sector 4')
df['locality'] = df['locality'].str.replace('sushant lok phase 1','sector 43')
df['locality'] = df['locality'].str.replace('sohna road','sector 48')
df['locality'] = df['locality'].str.replace('ashok vihar phase 2','sector 5')

In [12]:
df['locality'] = df['locality'].str.replace('rajiv colony','sector 33')
df['locality'] = df['locality'].str.replace('garauli kalan','sector 37')
df['locality'] = df['locality'].str.replace('bhawani enclave','sector 9')
df['locality'] = df['locality'].str.replace('iffco chowk','sector 17')
df['locality'] = df['locality'].str.replace('palam vihar','sector 2')
df['locality'] = df['locality'].str.replace('gwal pahari','sector 2')
df['locality'] = df['locality'].str.replace('malibu town','sector 47')
df['locality'] = df['locality'].str.replace('golf course road','sector 54')
df['locality'] = df['locality'].str.replace('chakkarpur','sector 28')
df['locality'] = df['locality'].str.replace('kanahi','sector 45')
df['locality'] = df['locality'].str.replace('dlf phase 5','sector 54')
df['locality'] = df['locality'].str.replace('nirvana country','sector 50')

In [13]:
df['locality'] = df['locality'].str.replace('dlf phase 2','sector 25')
df['locality'] = df['locality'].str.replace('dlf phase 3','sector 24')
df['locality'] = df['locality'].str.replace('heritage city','sector 25')
df['locality'] = df['locality'].str.replace('ambience island','sector 24')
df['locality'] = df['locality'].str.replace('suncity','sector 54')
df['locality'] = df['locality'].str.replace('sai kunj','sector 110')
df['locality'] = df['locality'].str.replace('manesar','sector 1')
df['locality'] = df['locality'].str.replace('imt manesar','sector 1')
df['locality'] = df['locality'].str.replace('mg road','sector 28')
df['locality'] = df['locality'].str.replace('sultanpur','sector 142')
df['locality'] = df['locality'].str.replace('civil lines','sector 15')
df['locality'] = df['locality'].str.replace('lajpat nagar','sector 4')

In [14]:
df['locality'] = df['locality'].str.replace('new gurgaon','sector 82')
df['locality'] = df['locality'].str.replace('surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('near pataudi chowk','sector 10')
df['locality'] = df['locality'].str.replace('cyber city','sector 24')
df['locality'] = df['locality'].str.replace('new colony','sector 7')
df['locality'] = df['locality'].str.replace('subhash nagar','sector 8')
df['locality'] = df['locality'].str.replace('ats marigold','sector 89')
df['locality'] = df['locality'].str.replace('adarsh nagar','sector 12')
df['locality'] = df['locality'].str.replace('sushant lok phase 3','sector 57')
df['locality'] = df['locality'].str.replace('carterpuri village','sector 23')
df['locality'] = df['locality'].str.replace('valley view estate','sector 2')
df['locality'] = df['locality'].str.replace('shanti nagar','sector 11')

In [15]:
df['locality'] = df['locality'].str.replace('sushant lok','sector 43')
df['locality'] = df['locality'].str.replace('mehrauli gurgaon road','sector 28')
df['locality'] = df['locality'].str.replace('laxman vihar phase 2','sector 4')
df['locality'] = df['locality'].str.replace('gurgaon faridabad road','sector 56')
df['locality'] = df['locality'].str.replace('dayanand colony','sector 6')
df['locality'] = df['locality'].str.replace('samaspur','sector 51')
df['locality'] = df['locality'].str.replace('nirvana country pocket h','sector 50')
df['locality'] = df['locality'].str.replace('patel nagar','sector 15')
df['locality'] = df['locality'].str.replace('surat nagar 1','sector 104')
df['locality'] = df['locality'].str.replace('sispal vihar','sector 49')
df['locality'] = df['locality'].str.replace('golf course ext road','sector 65')
df['locality'] = df['locality'].str.replace('shankar vihar','sector 104')

In [16]:
df['locality'] = df['locality'].str.replace('new palam vihar phase 2','sector 110')
df['locality'] = df['locality'].str.replace('palam vihar extension','sector 2')
df['locality'] = df['locality'].str.replace('saroop garden rajendra park','sector 105')
df['locality'] = df['locality'].str.replace('bptp','sector 37')
df['locality'] = df['locality'].str.replace('south city 1','sector 41')
df['locality'] = df['locality'].str.replace('dharam colony','sector 23')
df['locality'] = df['locality'].str.replace('rajendra park','sector 105')

In [17]:
df[~df['locality'].str.contains('sector')]['locality'].unique()

array([], dtype=object)

In [18]:
df['sector'] = df['locality'].str.extract(r"(\d+)").astype('int16')

In [19]:
df['sector'].unique()

array([  7,   3,  33,  61,  92, 102, 104,  88,  78,  81,  79,  90, 108,
        62,  89, 113,   1,  65,  48,  37, 110,  43,  68, 109, 106,  82,
        85,  28,  10,  21,  84,  71,  77,  67,  57,  95,  99, 103,  49,
        30,  86,  66,  15,   4,  22,  63,  52, 107,  12,   9,  17,   2,
        91,  70,  47,  54, 111,  41,  73,  36,  56,  83,  53,  72,  69,
        45,  14,  50,  25,  59,  24,  38, 112,  74,  60,  51,  39,  58,
        80,  55, 142,  93,  23,  76,  31,   8,  11,   5,   6, 105,  40],
      dtype=int16)

In [20]:
df['locality'].unique()

array(['sector 7', 'sector 3', 'sector 33', 'sector 61 gurgaon',
       'sector 92 gurgaon', 'sector 102', 'sector 104 gurgaon',
       'sector 88b gurgaon', 'sector 78 gurgaon', 'sector 81 gurgaon',
       'sector 79 gurgaon', 'sector 90 gurgaon', 'sector 108 gurgaon',
       'sector 62 gurgaon', 'sector 102 gurgaon', 'sector-33 sector 33',
       'sector 89 gurgaon', 'sector 113 gurgaon', 'sector 1 gurgaon',
       'sector 65 gurgaon', 'sector 48 gurgaon', 'sector 37c gurgaon',
       'sector 3 gurgaon', 'sector 110', 'sector 43 gurgaon',
       'sector 88a gurgaon', 'sector 68 gurgaon', 'sector 109 gurgaon',
       'sector 106 gurgaon', 'sector 82 gurgaon',
       'sector 3 phase 3 extension', 'sector 85 gurgaon',
       'sector 82a gurgaon', 'sector 28', 'sector 10a gurgaon',
       'sector 1a imt sector 1', 'sector 21', 'sector 84 gurgaon',
       'sector 33 gurgaon', 'sector 71 gurgaon', 'sector-7 housing board',
       'sector 77 gurgaon', 'sector 37d gurgaon', 'sector 67a gurgaon',
       'sector 57 gurgaon', 'sector 95 gurgaon', 'sector 99a gurgaon',
       'sector 103 gurgaon', 'sector 49 gurgaon', 'sector 30 gurgaon',
       'sector 86 gurgaon', 'sector 66 gurgaon', 'sector 15 part 1',
       'sector 4', 'sector 22 gurgaon', 'sector 63a gurgaon',
       'sector 95a gurgaon', 'sector 52 gurgaon', 'sector 67 gurgaon',
       'sector 43', 'sector 107 gurgaon', 'sector 12a gurgaon',
       'sector 33 road', 'sector 3 phase 2', 'sector 37', 'sector 9',
       'sector 99 gurgaon', 'sector 17', 'sector 2', 'sector 91 gurgaon',
       'near sector 1 market', 'sector 70 gurgaon', 'sector 70a gurgaon',
       'sector 7 gurgaon', 'sector 47', 'sector 54', 'sector 4 gurgaon',
       'sector 54 gurgaon', 'sector 111 gurgaon', 'sector 41 gurgaon',
       'sector 12 gurgaon', 'sector 73 gurgaon', 'sector 36 sector 33',
       'sector 56 gurgaon', 'sector 83 gurgaon', 'sector 53 gurgaon',
       'sector 72 gurgaon', 'sector 1 imt sector 1', 'sector 69 gurgaon',
       'sector 47 gurgaon', 'sector 63 gurgaon', 'sector 110 gurgaon',
       'sector 45', 'sector 9a gurgaon', 'sector 28 gurgaon',
       'sector 14 gurgaon', 'sector 50', 'sector 25', 'sector 59 gurgaon',
       'sector 24', 'sector 38 gurgaon', 'sector 15 gurgaon',
       'sector 112 gurgaon', 'sector 45 gurgaon', 'sector 74 gurgaon',
       'sector 60 gurgaon', 'sector 2 gurgaon', 'sector 51 gurgaon',
       'sector 50 gurgaon', 'sector 110 a gurgaon', 'sector 39 gurgaon',
       'sector 1', 'sector 58 gurgaon', 'imt sector 1',
       'sector 80 gurgaon', 'sector 55 gurgaon', 'sector 142',
       'sector 93 gurgaon', 'sector 23a gurgaon', 'sector 36a gurgaon',
       'sector 15', 'sector 76 gurgaon', 'sector 7, sector 7',
       'sector 31 gurgaon', 'sector 89 a gurgaon', 'sector 82',
       'sector 10', 'sector 8', 'sector 89', 'sector-2 sector 33',
       'sector 12', 'sector 37a gurgaon', 'sector 57', 'sector 23',
       'sector 11', 'sector 4 phase 2', 'sector 56', 'sector 36 gurgaon',
       'old delhi road, opp sector-14', 'sector 21 gurgaon',
       'sector 5 gurgaon', 'sector 6', 'sector 51', 'sector 50 pocket h',
       'sector 104', 'sector 49', 'sector 65', 'sector 110 phase 2',
       'sector 24 gurgaon', 'sector 2 extension', 'sector 105',
       'sector 4 urban estate', 'sector 105 gurgaon', 'sector 41',
       'sector 9 gurgaon', 'sector 40 gurgaon',
       'godrej aria , sector 79 , gurgaon'], dtype=object)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bhk             2911 non-null   int64
 2   bathroom        2911 non-null   int64
 3   balcony         2911 non-null   int64
 4   addl_room       2911 non-null   int64
 5   floor_rise      2911 non-null   object
 6   area_sqm        2911 non-null   float64
 7   area_type       2911 non-null   object
 8   age             2911 non-null   object
 9   society         2911 non-null   object
 10  locality        2911 non-null   object
 11  furnishDetails  2150 non-null   object
 12  nearby_loc      2911 non-null   object
 13  city            2911 non-null   object
 14  sector          2911 non-null   int16
dtypes: float64(2), int16(1), int64(4), object(8)
memory usage: 324.2+ KB

In [22]:
df.drop(columns=['locality'], inplace=True)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bhk             2911 non-null   int64
 2   bathroom        2911 non-null   int64
 3   balcony         2911 non-null   int64
 4   addl_room       2911 non-null   int64
 5   floor_rise      2911 non-null   object
 6   area_sqm        2911 non-null   float64
 7   area_type       2911 non-null   object
 8   age             2911 non-null   object
 9   society         2911 non-null   object
 10  furnishDetails  2150 non-null   object
 11  nearby_loc      2911 non-null   object
 12  city            2911 non-null   object
 13  sector          2911 non-null   int16
dtypes: float64(2), int16(1), int64(4), object(7)
memory usage: 301.5+ KB

In [24]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector
1428,0.78,3,3,3,1,low,112.41,carpet,new,signature global park,NaN,"['sector 55-56 metro', 'global city centre', '...",sohna,33
2449,0.20,1,2,2,0,low,27.96,carpet,new,zara aavaas,[],"['ardee mall', 'northern peripheral road', 'mp...",gurgaon,104
1112,0.90,2,2,3,1,mid,136.10,super built up,old,ashiana mulberry,"['2 wardrobe', '1 exhaust fan', '4 light', '1 ...","['discount department store', 'badshahpur sohn...",sohna,33
2339,0.50,3,2,2,0,low,55.46,carpet,new,breez global heights 88a,NaN,"['elan miracle', 'the esplanade mall', 'nh 352...",gurgaon,88

In [25]:
general_landmarks = ['mandir','bank','school','hospital','clinic','atm','nursing','dental',
                    'medical','eye','metro','station','railway','pizza','college','golf',
                    'chowk','lake','mall','highway','hwy','rly','railway','university',
                    'airport','community','petrol','cng','expressway','institute',
                    'park','healthcare','plaza','resort','waterpark','stadium','club',
                    'complex','pharmacy','inn','imt','academy','motors','dhaba','junction',
                    'tower','hilton','trauma','centre','center','dental','domino','moti mahal',
                    'pind baluchi','church','petroleum','reliance','naval','mcdonald','bar',
                    'liquor','wine','beer','whiskey','rum','scotch','cafe','distillery','hotel',
                    'spa','sagar ratna','store','national','birla','hyatt','lemontree','lounge',
                    'bakery','oil','coffee','starbucks','belgian','waffle','petrol','cng','isbt',
                    'sports','hill','pvr','helipad','huda','cinema','bazaar','farm','expy']

In [26]:
def landmark_clean(row):
    row = row.replace('[','').replace(']','').replace("'","").replace("\\","").split(",")
    row_ret = []
    for item in row:
        for gen_lmk in general_landmarks:
            if gen_lmk in item:
                row_ret.append(item)
    return row_ret

In [27]:
df['landmarks'] = df['nearby_loc'].apply(landmark_clean)
df.drop(columns=['nearby_loc'], inplace=True)

In [28]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,city,sector,landmarks
2610,0.27,2,2,1,0,high,42.50,carpet,new,mvn athens,"['2 wardrobe', '1 water purifier', '3 fan', '1...",sohna,33,"[sbi atm, axis bank atm, axis bank atm, uco..."
577,0.75,3,2,2,0,low,123.19,super built up,new,sare green parc phase 3,NaN,gurgaon,92,"[huda metro station, huda metro station, huda ..."
2032,7.52,4,4,3,0,high,367.52,built up,under construction,dlf the arbour,"['1 light', 'no ac', 'no bed', 'no chimney', '...",gurgaon,63,"[radhakrishna shani mandir, pracksht hospital..."
2286,0.36,1,1,1,0,high,37.63,carpet,new,lotus homz,NaN,gurgaon,111,"[sector 23 huda market, huda market, jai vis..."

In [29]:
for row in df['furnishDetails']:
    row = str(row).replace('[','').replace(']','').replace("'","").replace('no','0').strip().split(",")
    for item in row:
        if item != 'nan':
            name_obj = re.findall(r"([a-zA-Z/s]+)", item)
            if name_obj is not None:
                name = " ".join(name_obj)
                
            count_obj = re.search(r"(\d+)", item)
            if count_obj is not None:
                count = count_obj.group()
                df[name]=count

df.drop(columns=['furnishDetails'], inplace=True)

In [30]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,city,sector,landmarks,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier
2691,1.08,2,2,3,0,high,83.61204,carpet,mid aged,godrej nature plus,sohna,33,"[signature global infinity mall sohna, badsha...",6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
2560,4.30,4,5,3,1,mid,288.00000,carpet,new,vipul world floors,gurgaon,48,"[ icici bank atm, icici bank atm, standard c...",6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
1291,1.34,3,3,3,1,high,166.30000,super built up,new,indiabulls centrum park,gurgaon,103,"[gurgaon dreamz mall, huda market, dwarka ex...",6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
1790,0.65,2,2,2,1,high,120.77000,super built up,old,shree vardhman flora,gurgaon,90,"[iris broadway mall, dwarka expressway, sara...",6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0

In [31]:
df.columns

Index(['price_cr', 'bhk', 'bathroom', 'balcony', 'addl_room', 'floor_rise',
       'area_sqm', 'area_type', 'age', 'society', 'city', 'sector',
       'landmarks', 'fan', 'light', 'wardrobe', 'ac', 'bed', 'chimney',
       'curtains', 'dining table', 'exhaust fan', 'geyser', 'modular kitchen',
       'microwave', 'fridge', 'sofa', 'stove', 'tv', 'washing machine',
       'water purifier'],
      dtype='object')

In [32]:
df = df.reindex(columns=['price_cr', 'bhk', 'bathroom', 'balcony', 'addl_room', 'floor_rise',
       'area_sqm', 'area_type', 'age', 'fan', 'light', 'wardrobe', 'ac', 'bed', 'chimney',
       'curtains', 'dining table', 'exhaust fan', 'geyser', 'modular kitchen',
       'microwave', 'fridge', 'sofa', 'stove', 'tv', 'washing machine',
       'water purifier', 'society', 'sector', 'city', 'landmarks'])

In [33]:
df.sample(3)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,society,sector,city,landmarks
1188,0.81,3,3,3,1,low,240.43,super built up,old,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,hsiidc sidco aravali,1,manesar,"[pooja clinic, dr. sahil clinic, prakash hos..."
1588,1.45,3,3,3,0,low,176.52,super built up,old,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,kanchanjanga tower,56,gurgaon,"[sector metro station, sector metro station, ..."
1382,0.43,2,2,1,1,mid,46.54,carpet,new,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,pyramid urban homes 2,86,gurgaon,"[sapphire 83 mall, manesar toll plaza - kherk..."

In [34]:
df.to_csv('05_flats_featEngineered.csv')