In [1]:
import numpy as np
import pandas as pd
import re
pd.set_option('display.max_columns', None)

import warnings as wr
wr.filterwarnings('ignore')

In [2]:
df = pd.read_csv('03_flats_cleaned.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bhk             2911 non-null   int64
 2   bathroom        2911 non-null   int64
 3   balcony         2911 non-null   int64
 4   addl_room       2911 non-null   int64
 5   floor_rise      2911 non-null   object
 6   area_sqm        2911 non-null   float64
 7   area_type       2911 non-null   object
 8   age             2911 non-null   object
 9   society         2911 non-null   object
 10  locality        2911 non-null   object
 11  furnishDetails  2150 non-null   object
 12  nearby_loc      2911 non-null   object
dtypes: float64(2), int64(4), object(7)
memory usage: 295.8+ KB

In [4]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,locality,furnishDetails,nearby_loc
1251,3.95,3,4,2,1,high,217.67,super built up,new,sobha city,sector 108 gurgaon,"['4 geyser', 'no ac', 'no bed', 'no chimney', ...","['dwarka sector 21', 'dwarka expressway', 'vas..."
1875,1.68,3,3,3,1,mid,236.44,super built up,old,sbtl caladium,sector 109 gurgaon,NaN,"['palam vihar vyapar kendra', 'chirag hospital..."
2496,0.55,2,2,3,0,low,76.37,carpet,under construction,signature global park,sohna,NaN,"['sector 55-56 metro', 'global city centre', '..."
1089,3.10,3,4,3,1,mid,231.42,super built up,old,the close south,nirvana country,"['4 wardrobe', '8 fan', '1 exhaust fan', '3 ge...","['fresco market', 'emerald plaza', 'tagore pub..."

In [5]:
df['locality'].unique()

array(['krishna colony', 'ashok vihar', 'sohna', 'sector 61 gurgaon',
       'sector 92 gurgaon', 'dwarka expressway gurgaon',
       'sector 104 gurgaon', 'sector 88b gurgaon', 'sector 78 gurgaon',
       'sector 81 gurgaon', 'sector 79 gurgaon', 'sector 90 gurgaon',
       'sector 108 gurgaon', 'sector 62 gurgaon', 'sector 102 gurgaon',
       'sector-33 sohna', 'sector 89 gurgaon', 'sector 113 gurgaon',
       'sector 1 gurgaon', 'sector 65 gurgaon', 'sector 48 gurgaon',
       'sector 37c gurgaon', 'sector 3 gurgaon', 'new palam vihar',
       'sector 43 gurgaon', 'sector 88a gurgaon', 'sector 68 gurgaon',
       'sector 109 gurgaon', 'sector 106 gurgaon', 'sector 82 gurgaon',
       'ashok vihar phase 3 extension', 'sector 85 gurgaon',
       'sector 82a gurgaon', 'dlf phase 4', 'sector 10a gurgaon',
       'sector 1a imt manesar', 'block a surya vihar',
       'sector 84 gurgaon', 'sector 33 gurgaon', 'sector 71 gurgaon',
       'sector-7 housing board', 'sector 77 gurgaon',
       'sector 37d gurgaon', 'sector 67a gurgaon', 'sector 57 gurgaon',
       'sector 95 gurgaon', 'sector 99a gurgaon', 'sector 103 gurgaon',
       'sector 49 gurgaon', 'sector 30 gurgaon', 'sector 86 gurgaon',
       'sector 66 gurgaon', 'sector 15 part 1', 'laxman vihar',
       'sector 22 gurgaon', 'sector 63a gurgaon', 'sector 95a gurgaon',
       'sector 52 gurgaon', 'sector 67 gurgaon', 'sushant lok phase 1',
       'sector 107 gurgaon', 'sector 12a gurgaon', 'sohna road',
       'ashok vihar phase 2', 'rajiv colony', 'garauli kalan',
       'bhawani enclave', 'sector 99 gurgaon', 'iffco chowk',
       'palam vihar', 'sector 91 gurgaon', 'near sector 1 market',
       'sector 70 gurgaon', 'sector 70a gurgaon', 'gwal pahari',
       'sector 7 gurgaon', 'malibu town', 'golf course road',
       'sector 4 gurgaon', 'sector 54 gurgaon', 'sector 111 gurgaon',
       'chakkarpur', 'sector 41 gurgaon', 'sector 12 gurgaon',
       'sector 73 gurgaon', 'sector 36 sohna', 'sector 56 gurgaon',
       'sector 83 gurgaon', 'sector 53 gurgaon', 'sector 72 gurgaon',
       'sector 1 imt manesar', 'sector 69 gurgaon', 'sector 47 gurgaon',
       'sector 63 gurgaon', 'sector 110 gurgaon', 'kanahi', 'dlf phase 5',
       'sector 9a gurgaon', 'sector 28 gurgaon', 'sector 14 gurgaon',
       'nirvana country', 'dlf phase 2', 'sector 59 gurgaon',
       'dlf phase 3', 'heritage city', 'sector 38 gurgaon',
       'sector 15 gurgaon', 'ambience island', 'sector 112 gurgaon',
       'sector 45 gurgaon', 'sector 74 gurgaon', 'sector 60 gurgaon',
       'sector 2 gurgaon', 'sector 51 gurgaon', 'sector 50 gurgaon',
       'suncity', 'sector 110 a gurgaon', 'sector 39 gurgaon', 'sai kunj',
       'manesar', 'sector 58 gurgaon', 'imt manesar', 'sector 80 gurgaon',
       'mg road', 'sector 55 gurgaon', 'sultanpur', 'sector 93 gurgaon',
       'sector 23a gurgaon', 'sector 36a gurgaon', 'civil lines',
       'sector 76 gurgaon', 'new colony, sector 7', 'sector 31 gurgaon',
       'lajpat nagar', 'sector 89 a gurgaon', 'new gurgaon',
       'surya vihar', 'near pataudi chowk', 'cyber city', 'new colony',
       'subhash nagar', 'ats marigold', 'sector-2 sohna', 'adarsh nagar',
       'sector 37a gurgaon', 'sushant lok phase 3', 'carterpuri village',
       'valley view estate', 'shanti nagar', 'sushant lok',
       'mehrauli gurgaon road', 'laxman vihar phase 2',
       'gurgaon faridabad road', 'sector 36 gurgaon',
       'old delhi road, opp sector-14', 'sector 21 gurgaon',
       'sector 5 gurgaon', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'sector 24 gurgaon',
       'palam vihar extension', 'saroop garden rajendra park',
       'sector 4 urban estate', 'bptp', 'sector 105 gurgaon',
       'south city 1', 'sector 9 gurgaon', 'sector 40 gurgaon',
       'dharam colony', 'rajendra park',
       'godrej aria , sector 79 , gurgaon'], dtype=object)

In [6]:
df['city'] = np.where(df['locality'].str.contains('imt|manesar'), 'manesar',
                     np.where(df['locality'].str.contains('sohna'), 'sohna', 'gurgaon'))

In [7]:
df['city'].unique()

array(['gurgaon', 'sohna', 'manesar'], dtype=object)

In [8]:
#localities with sector not mentioned

In [9]:
df[~df['locality'].str.contains('sector')]['locality'].unique()

array(['krishna colony', 'ashok vihar', 'sohna',
       'dwarka expressway gurgaon', 'new palam vihar',
       'ashok vihar phase 3 extension', 'dlf phase 4',
       'block a surya vihar', 'laxman vihar', 'sushant lok phase 1',
       'sohna road', 'ashok vihar phase 2', 'rajiv colony',
       'garauli kalan', 'bhawani enclave', 'iffco chowk', 'palam vihar',
       'gwal pahari', 'malibu town', 'golf course road', 'chakkarpur',
       'kanahi', 'dlf phase 5', 'nirvana country', 'dlf phase 2',
       'dlf phase 3', 'heritage city', 'ambience island', 'suncity',
       'sai kunj', 'manesar', 'imt manesar', 'mg road', 'sultanpur',
       'civil lines', 'lajpat nagar', 'new gurgaon', 'surya vihar',
       'near pataudi chowk', 'cyber city', 'new colony', 'subhash nagar',
       'ats marigold', 'adarsh nagar', 'sushant lok phase 3',
       'carterpuri village', 'valley view estate', 'shanti nagar',
       'sushant lok', 'mehrauli gurgaon road', 'laxman vihar phase 2',
       'gurgaon faridabad road', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'palam vihar extension',
       'saroop garden rajendra park', 'bptp', 'south city 1',
       'dharam colony', 'rajendra park'], dtype=object)

In [10]:
#changing these localities to their respective sectors

In [11]:
df['locality'] = df['locality'].str.replace('krishna colony','sector 7')
df['locality'] = df['locality'].str.replace('ashok vihar','sector 3')
df['locality'] = df['locality'].str.replace('sohna','sector 33')
df['locality'] = df['locality'].str.replace('dwarka expressway gurgaon','sector 102')
df['locality'] = df['locality'].str.replace('new palam vihar','sector 110')
df['locality'] = df['locality'].str.replace('ashok vihar phase 3 extension','sector 3')
df['locality'] = df['locality'].str.replace('dlf phase 4','sector 28')
df['locality'] = df['locality'].str.replace('block a surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('laxman vihar','sector 4')
df['locality'] = df['locality'].str.replace('sushant lok phase 1','sector 43')
df['locality'] = df['locality'].str.replace('sohna road','sector 48')
df['locality'] = df['locality'].str.replace('ashok vihar phase 2','sector 5')

In [12]:
df['locality'] = df['locality'].str.replace('rajiv colony','sector 33')
df['locality'] = df['locality'].str.replace('garauli kalan','sector 37')
df['locality'] = df['locality'].str.replace('bhawani enclave','sector 9')
df['locality'] = df['locality'].str.replace('iffco chowk','sector 17')
df['locality'] = df['locality'].str.replace('palam vihar','sector 2')
df['locality'] = df['locality'].str.replace('gwal pahari','sector 2')
df['locality'] = df['locality'].str.replace('malibu town','sector 47')
df['locality'] = df['locality'].str.replace('golf course road','sector 54')
df['locality'] = df['locality'].str.replace('chakkarpur','sector 28')
df['locality'] = df['locality'].str.replace('kanahi','sector 45')
df['locality'] = df['locality'].str.replace('dlf phase 5','sector 54')
df['locality'] = df['locality'].str.replace('nirvana country','sector 50')

In [13]:
df['locality'] = df['locality'].str.replace('dlf phase 2','sector 25')
df['locality'] = df['locality'].str.replace('dlf phase 3','sector 24')
df['locality'] = df['locality'].str.replace('heritage city','sector 25')
df['locality'] = df['locality'].str.replace('ambience island','sector 24')
df['locality'] = df['locality'].str.replace('suncity','sector 54')
df['locality'] = df['locality'].str.replace('sai kunj','sector 110')
df['locality'] = df['locality'].str.replace('manesar','sector 1')
df['locality'] = df['locality'].str.replace('imt manesar','sector 1')
df['locality'] = df['locality'].str.replace('mg road','sector 28')
df['locality'] = df['locality'].str.replace('sultanpur','sector 142')
df['locality'] = df['locality'].str.replace('civil lines','sector 15')
df['locality'] = df['locality'].str.replace('lajpat nagar','sector 4')

In [14]:
df['locality'] = df['locality'].str.replace('new gurgaon','sector 82')
df['locality'] = df['locality'].str.replace('surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('near pataudi chowk','sector 10')
df['locality'] = df['locality'].str.replace('cyber city','sector 24')
df['locality'] = df['locality'].str.replace('new colony','sector 7')
df['locality'] = df['locality'].str.replace('subhash nagar','sector 8')
df['locality'] = df['locality'].str.replace('ats marigold','sector 89')
df['locality'] = df['locality'].str.replace('adarsh nagar','sector 12')
df['locality'] = df['locality'].str.replace('sushant lok phase 3','sector 57')
df['locality'] = df['locality'].str.replace('carterpuri village','sector 23')
df['locality'] = df['locality'].str.replace('valley view estate','sector 2')
df['locality'] = df['locality'].str.replace('shanti nagar','sector 11')

In [15]:
df['locality'] = df['locality'].str.replace('sushant lok','sector 43')
df['locality'] = df['locality'].str.replace('mehrauli gurgaon road','sector 28')
df['locality'] = df['locality'].str.replace('laxman vihar phase 2','sector 4')
df['locality'] = df['locality'].str.replace('gurgaon faridabad road','sector 56')
df['locality'] = df['locality'].str.replace('dayanand colony','sector 6')
df['locality'] = df['locality'].str.replace('samaspur','sector 51')
df['locality'] = df['locality'].str.replace('nirvana country pocket h','sector 50')
df['locality'] = df['locality'].str.replace('patel nagar','sector 15')
df['locality'] = df['locality'].str.replace('surat nagar 1','sector 104')
df['locality'] = df['locality'].str.replace('sispal vihar','sector 49')
df['locality'] = df['locality'].str.replace('golf course ext road','sector 65')
df['locality'] = df['locality'].str.replace('shankar vihar','sector 104')

In [16]:
df['locality'] = df['locality'].str.replace('new palam vihar phase 2','sector 110')
df['locality'] = df['locality'].str.replace('palam vihar extension','sector 2')
df['locality'] = df['locality'].str.replace('saroop garden rajendra park','sector 105')
df['locality'] = df['locality'].str.replace('bptp','sector 37')
df['locality'] = df['locality'].str.replace('south city 1','sector 41')
df['locality'] = df['locality'].str.replace('dharam colony','sector 23')
df['locality'] = df['locality'].str.replace('rajendra park','sector 105')

In [17]:
df['sector'] = df['locality'].str.extract(r"(\d+)").astype('int16')

In [18]:
df['sector'].unique()

array([  7,   3,  33,  61,  92, 102, 104,  88,  78,  81,  79,  90, 108,
        62,  89, 113,   1,  65,  48,  37, 110,  43,  68, 109, 106,  82,
        85,  28,  10,  21,  84,  71,  77,  67,  57,  95,  99, 103,  49,
        30,  86,  66,  15,   4,  22,  63,  52, 107,  12,   9,  17,   2,
        91,  70,  47,  54, 111,  41,  73,  36,  56,  83,  53,  72,  69,
        45,  14,  50,  25,  59,  24,  38, 112,  74,  60,  51,  39,  58,
        80,  55, 142,  93,  23,  76,  31,   8,  11,   5,   6, 105,  40],
      dtype=int16)

In [19]:
df['locality'].unique()

array(['sector 7', 'sector 3', 'sector 33', 'sector 61 gurgaon',
       'sector 92 gurgaon', 'sector 102', 'sector 104 gurgaon',
       'sector 88b gurgaon', 'sector 78 gurgaon', 'sector 81 gurgaon',
       'sector 79 gurgaon', 'sector 90 gurgaon', 'sector 108 gurgaon',
       'sector 62 gurgaon', 'sector 102 gurgaon', 'sector-33 sector 33',
       'sector 89 gurgaon', 'sector 113 gurgaon', 'sector 1 gurgaon',
       'sector 65 gurgaon', 'sector 48 gurgaon', 'sector 37c gurgaon',
       'sector 3 gurgaon', 'sector 110', 'sector 43 gurgaon',
       'sector 88a gurgaon', 'sector 68 gurgaon', 'sector 109 gurgaon',
       'sector 106 gurgaon', 'sector 82 gurgaon',
       'sector 3 phase 3 extension', 'sector 85 gurgaon',
       'sector 82a gurgaon', 'sector 28', 'sector 10a gurgaon',
       'sector 1a imt sector 1', 'sector 21', 'sector 84 gurgaon',
       'sector 33 gurgaon', 'sector 71 gurgaon', 'sector-7 housing board',
       'sector 77 gurgaon', 'sector 37d gurgaon', 'sector 67a gurgaon',
       'sector 57 gurgaon', 'sector 95 gurgaon', 'sector 99a gurgaon',
       'sector 103 gurgaon', 'sector 49 gurgaon', 'sector 30 gurgaon',
       'sector 86 gurgaon', 'sector 66 gurgaon', 'sector 15 part 1',
       'sector 4', 'sector 22 gurgaon', 'sector 63a gurgaon',
       'sector 95a gurgaon', 'sector 52 gurgaon', 'sector 67 gurgaon',
       'sector 43', 'sector 107 gurgaon', 'sector 12a gurgaon',
       'sector 33 road', 'sector 3 phase 2', 'sector 37', 'sector 9',
       'sector 99 gurgaon', 'sector 17', 'sector 2', 'sector 91 gurgaon',
       'near sector 1 market', 'sector 70 gurgaon', 'sector 70a gurgaon',
       'sector 7 gurgaon', 'sector 47', 'sector 54', 'sector 4 gurgaon',
       'sector 54 gurgaon', 'sector 111 gurgaon', 'sector 41 gurgaon',
       'sector 12 gurgaon', 'sector 73 gurgaon', 'sector 36 sector 33',
       'sector 56 gurgaon', 'sector 83 gurgaon', 'sector 53 gurgaon',
       'sector 72 gurgaon', 'sector 1 imt sector 1', 'sector 69 gurgaon',
       'sector 47 gurgaon', 'sector 63 gurgaon', 'sector 110 gurgaon',
       'sector 45', 'sector 9a gurgaon', 'sector 28 gurgaon',
       'sector 14 gurgaon', 'sector 50', 'sector 25', 'sector 59 gurgaon',
       'sector 24', 'sector 38 gurgaon', 'sector 15 gurgaon',
       'sector 112 gurgaon', 'sector 45 gurgaon', 'sector 74 gurgaon',
       'sector 60 gurgaon', 'sector 2 gurgaon', 'sector 51 gurgaon',
       'sector 50 gurgaon', 'sector 110 a gurgaon', 'sector 39 gurgaon',
       'sector 1', 'sector 58 gurgaon', 'imt sector 1',
       'sector 80 gurgaon', 'sector 55 gurgaon', 'sector 142',
       'sector 93 gurgaon', 'sector 23a gurgaon', 'sector 36a gurgaon',
       'sector 15', 'sector 76 gurgaon', 'sector 7, sector 7',
       'sector 31 gurgaon', 'sector 89 a gurgaon', 'sector 82',
       'sector 10', 'sector 8', 'sector 89', 'sector-2 sector 33',
       'sector 12', 'sector 37a gurgaon', 'sector 57', 'sector 23',
       'sector 11', 'sector 4 phase 2', 'sector 56', 'sector 36 gurgaon',
       'old delhi road, opp sector-14', 'sector 21 gurgaon',
       'sector 5 gurgaon', 'sector 6', 'sector 51', 'sector 50 pocket h',
       'sector 104', 'sector 49', 'sector 65', 'sector 110 phase 2',
       'sector 24 gurgaon', 'sector 2 extension', 'sector 105',
       'sector 4 urban estate', 'sector 105 gurgaon', 'sector 41',
       'sector 9 gurgaon', 'sector 40 gurgaon',
       'godrej aria , sector 79 , gurgaon'], dtype=object)

In [20]:
df.drop(columns=['locality'], inplace=True)

In [21]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector
687,1.15,2,2,3,1,high,123.10,super built up,new,indiabulls centrum park,"['2 wardrobe', '1 water purifier', '3 fan', '2...","['gurgaon dreamz mall', 'huda market, sector 1...",gurgaon,103
1997,0.90,3,3,3,1,low,240.43,super built up,old,hsiidc sidco aravali,"['1 water purifier', '5 fan', '1 fridge', '1 d...","['pooja clinic', 'dr. sahil clinic', 'prakash ...",manesar,1
398,1.71,3,3,3,1,mid,203.55,built up,new,bptp terra,"['6 fan', '5 light', 'no ac', 'no bed', 'no ch...","['airia mall', 'dwarka expressway', 'golf cour...",gurgaon,37
2550,1.20,3,3,2,0,low,132.20,built up,under construction,smart world gems,NaN,"['sant soordas sihi metro station', 'airia mal...",gurgaon,89

In [22]:
# handling nearby_loc feature
import ast

df['nearby_1'] = df['nearby_loc'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

df['landmark_count'] = df['nearby_1'].apply(lambda x: len(x))

In [23]:
from collections import Counter

stopwords = {'the', 'a', 'an', 'and', 'of', 'in', 'at', 'to', 'is', 'for', 'on'}

all_words = []
for landmark_list in df['nearby_1']:
    for landmark in landmark_list:
        # Lowercase, remove special characters, split into words
        words = re.sub(r'[^a-z0-9\s]', '', landmark.lower()).split()
        filtered = [w for w in words if w not in stopwords and len(w) > 2]
        all_words.extend(filtered)

word_freq = Counter(all_words)

In [24]:
top_n = 100
nearby_freq = pd.DataFrame(word_freq.most_common(top_n), columns=['word', 'frequency'])

In [25]:
not_landmark = ('gurgaon','sector','gandhi','indira','dwarka','gurugram','sohna',
                'igi','delhi','manesar','imt','5556','sec')

general_landmarks = nearby_freq[~nearby_freq['word'].isin(not_landmark)].iloc[:,0].tolist()

In [26]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector,nearby_1,landmark_count
1659,1.40,2,2,3,0,high,127.09,super built up,new,shapoorji pallonji joyville gurugram,"['4 ac', '1 modular kitchen', '1 chimney', 'no...","['khan market', 'the esplanade mall', 'dwarka ...",gurgaon,102,"[khan market, the esplanade mall, dwarka expre...",13
675,1.85,4,4,2,0,high,186.74,super built up,new,tulip violet,"['4 wardrobe', '5 fan', '1 exhaust fan', '1 di...","['airia mall sector 68', 'southern peripheral ...",gurgaon,69,"[airia mall sector 68, southern peripheral roa...",10
811,2.00,4,4,2,0,high,186.74,super built up,new,tulip violet,"['1 modular kitchen', 'no ac', 'no bed', 'no c...","['airia mall sector 68', 'southern peripheral ...",gurgaon,69,"[airia mall sector 68, southern peripheral roa...",10
722,1.19,2,2,3,1,high,151.25,super built up,new,godrej oasis,"['2 wardrobe', '5 fan', '1 geyser', '5 light',...","['double infinity market', 'pataudi road', 'dw...",gurgaon,88,"[double infinity market, pataudi road, dwarka ...",7

In [27]:
landmark_dict = {
    'has_hospital_or_clinic': ['hospital','nursing','clinic','health care'],
    'has_police_stn': ['police'],
    'has_fire_stn': ['fire'],
    'has_mall': ['mall'],
    'has_market': ['pharmacy','market'],
    'has_park': ['park'],
    'has_bank_or_atm': ['atm','bank'],
    'has_institute': ['institute','school','vidyalaya','college','university','academy'],
    'has_airport': ['airport'],
    'has_rly_stn': ['railway station','rly station','railway stn','rly stn'],
    'has_metro_stn': ['metro'],
    'has_expy': ['expressway','expy'],
    'has_petrol_pump': ['petrol','cng','oil','petroleum'],
    'has_hotel': ['hotel','inn','radisson','lemontree'],
    'has_temple_or_church': ['temple','mandir','church'],
    'has_famous_chowk': ['chowk'],
    'has_club': ['club'],
    'has_stadium': ['stadium'],
    'has_restro_cafe': ['restaurant','cafe','food court','dhaba','burger','pizza','dominos','mcdonald','coffee']
}

In [28]:
for key, values in landmark_dict.items():
    df[key] = 0
    for index, df_nearby in df.iterrows():
        landmarks = df_nearby['nearby_loc'].replace("[",'').replace("]",'').replace("'",'').split(",")
        landmarks = [landmark.strip() for landmark in landmarks if len(landmark.strip())>2]
        for landmark in landmarks:
            for val in values:
                if val in landmark:
                    df.loc[index,key] += 1
                    break

In [29]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector,nearby_1,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe
578,3.65,3,4,3,1,high,250.65,super built up,new,ireo victory valley,"['6 fan', '5 light', '6 ac', '1 chimney', '1 m...","['aipl joy street mall', 'golf course extensio...",gurgaon,67,"[aipl joy street mall, golf course extension r...",11,1,0,0,1,0,1,0,2,1,0,0,0,0,1,0,0,0,0,0
2339,0.50,3,2,2,0,low,55.46,carpet,new,breez global heights 88a,NaN,"['elan miracle', 'the esplanade mall', 'nh 352...",gurgaon,88,"[elan miracle, the esplanade mall, nh 352w, de...",9,1,0,0,1,0,0,0,2,1,0,0,1,0,0,0,0,0,0,0
1123,1.32,3,3,1,1,high,145.67,super built up,new,tulip violet,"['2 wardrobe', '6 fan', '1 exhaust fan', '9 li...","['airia mall sector 68', 'southern peripheral ...",gurgaon,69,"[airia mall sector 68, southern peripheral roa...",10,1,0,0,1,0,1,0,2,1,0,0,0,0,1,0,0,0,0,0
912,0.78,2,2,2,1,mid,135.36,super built up,new,eldeco accolade,"['2 bed', '2 wardrobe', '2 fan', '1 exhaust fa...","['global city centre', 'sohna road', 'damdama ...",sohna,33,"[global city centre, sohna road, damdama more,...",7,1,0,0,0,0,0,0,2,0,0,0,1,0,0,0,0,0,0,0

In [30]:
for row in df['furnishDetails']:
    row = str(row).replace('[','').replace(']','').replace("'","").replace('no','0').strip().split(",")
    for item in row:
        if item != 'nan':
            name_obj = re.findall(r"([a-zA-Z/s]+)", item)
            if name_obj is not None:
                name = " ".join(name_obj)
                
            count_obj = re.search(r"(\d+)", item)
            if count_obj is not None:
                count = count_obj.group()
                df[name]=count

df.drop(columns=['nearby_1','nearby_loc','furnishDetails'], inplace=True)

In [31]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,city,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier
1955,0.28,2,2,2,0,high,60.39,super built up,new,gls arawali homes,sohna,33,6,0,0,0,0,0,0,0,0,1,0,0,2,0,0,0,1,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
884,1.55,3,3,3,1,mid,181.16,super built up,new,shree vardhman victoria,gurgaon,70,15,2,0,0,1,0,2,3,0,0,0,0,0,1,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
195,0.60,2,2,3,0,high,65.96,carpet,new,lotus homz,gurgaon,111,15,2,1,0,0,2,2,2,3,0,0,1,0,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
1468,1.70,3,3,3,0,high,162.12,super built up,new,ats kocoon,gurgaon,109,15,0,0,0,0,1,0,3,3,1,0,0,0,1,0,1,0,1,1,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 50 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   price_cr                2904 non-null   float64
 1   bhk                     2911 non-null   int64
 2   bathroom                2911 non-null   int64
 3   balcony                 2911 non-null   int64
 4   addl_room               2911 non-null   int64
 5   floor_rise              2911 non-null   object
 6   area_sqm                2911 non-null   float64
 7   area_type               2911 non-null   object
 8   age                     2911 non-null   object
 9   society                 2911 non-null   object
 10  city                    2911 non-null   object
 11  sector                  2911 non-null   int16
 12  landmark_count          2911 non-null   int64
 13  has_hospital_or_clinic  2911 non-null   int64
 14  has_police_stn          2911 non-null   int64
 15  has_fire_stn            2911 non-null   int64
 16  has_mall                2911 non-null   int64
 17  has_market              2911 non-null   int64
 18  has_park                2911 non-null   int64
 19  has_bank_or_atm         2911 non-null   int64
 20  has_institute           2911 non-null   int64
 21  has_airport             2911 non-null   int64
 22  has_rly_stn             2911 non-null   int64
 23  has_metro_stn           2911 non-null   int64
 24  has_expy                2911 non-null   int64
 25  has_petrol_pump         2911 non-null   int64
 26  has_hotel               2911 non-null   int64
 27  has_temple_or_church    2911 non-null   int64
 28  has_famous_chowk        2911 non-null   int64
 29  has_club                2911 non-null   int64
 30  has_stadium             2911 non-null   int64
 31  has_restro_cafe         2911 non-null   int64
 32  fan                     2911 non-null   object
 33  light                   2911 non-null   object
 34  wardrobe                2911 non-null   object
 35  ac                      2911 non-null   object
 36  bed                     2911 non-null   object
 37  chimney                 2911 non-null   object
 38  curtains                2911 non-null   object
 39  dining table            2911 non-null   object
 40  exhaust fan             2911 non-null   object
 41  geyser                  2911 non-null   object
 42  modular kitchen         2911 non-null   object
 43  microwave               2911 non-null   object
 44  fridge                  2911 non-null   object
 45  sofa                    2911 non-null   object
 46  stove                   2911 non-null   object
 47  tv                      2911 non-null   object
 48  washing machine         2911 non-null   object
 49  water purifier          2911 non-null   object
dtypes: float64(2), int16(1), int64(24), object(23)
memory usage: 1.1+ MB

In [33]:
df.columns

Index(['price_cr', 'bhk', 'bathroom', 'balcony', 'addl_room', 'floor_rise',
       'area_sqm', 'area_type', 'age', 'society', 'city', 'sector',
       'landmark_count', 'has_hospital_or_clinic', 'has_police_stn',
       'has_fire_stn', 'has_mall', 'has_market', 'has_park', 'has_bank_or_atm',
       'has_institute', 'has_airport', 'has_rly_stn', 'has_metro_stn',
       'has_expy', 'has_petrol_pump', 'has_hotel', 'has_temple_or_church',
       'has_famous_chowk', 'has_club', 'has_stadium', 'has_restro_cafe', 'fan',
       'light', 'wardrobe', 'ac', 'bed', 'chimney', 'curtains', 'dining table',
       'exhaust fan', 'geyser', 'modular kitchen', 'microwave', 'fridge',
       'sofa', 'stove', 'tv', 'washing machine', 'water purifier'],
      dtype='object')

In [34]:
int_cols = ['bhk','bathroom','balcony','addl_room','sector','landmark_count',
            'has_hospital_or_clinic','has_police_stn','has_fire_stn','has_mall',
            'has_market','has_park','has_bank_or_atm','has_institute','has_airport',
            'has_rly_stn','has_metro_stn','has_expy','has_petrol_pump','has_hotel',
            'has_temple_or_church','has_famous_chowk','has_club','has_stadium',
            'has_restro_cafe','fan','light','wardrobe','ac','bed','chimney',
            'curtains','dining table','exhaust fan','geyser','modular kitchen',
            'microwave','fridge','sofa','stove','tv','washing machine','water purifier']

for col in int_cols:
    df[col] = df[col].astype('int16')

In [35]:
df = df.reindex(columns=['price_cr','area_sqm','bhk','bathroom','balcony','addl_room','sector',
                         'landmark_count','has_hospital_or_clinic','has_police_stn','has_fire_stn',
                         'has_mall','has_market','has_park','has_bank_or_atm','has_institute',
                         'has_airport','has_rly_stn','has_metro_stn','has_expy','has_petrol_pump',
                         'has_hotel','has_temple_or_church','has_famous_chowk','has_club','has_stadium',
                         'has_restro_cafe','fan','light','wardrobe','ac','bed','chimney','curtains',
                         'dining table','exhaust fan','geyser','modular kitchen','microwave','fridge',
                         'sofa','stove','tv','washing machine','water purifier','area_type','floor_rise',
                         'age','society','city'])

In [36]:
df.sample(3)

,price_cr,area_sqm,bhk,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,area_type,floor_rise,age,society,city
2688,0.65,133.82,3,3,3,0,92,8,4,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,super built up,low,old,sare crescent parc royal greens phase 1,gurgaon
1985,1.05,91.79,2,2,2,0,50,45,12,0,0,0,2,3,10,1,0,0,0,0,0,0,1,0,1,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,carpet,low,old,woodstock floors,gurgaon
856,2.20,159.51,3,4,3,1,63,6,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,super built up,high,old,dhoot time residency,gurgaon

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 50 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   price_cr                2904 non-null   float64
 1   area_sqm                2911 non-null   float64
 2   bhk                     2911 non-null   int16
 3   bathroom                2911 non-null   int16
 4   balcony                 2911 non-null   int16
 5   addl_room               2911 non-null   int16
 6   sector                  2911 non-null   int16
 7   landmark_count          2911 non-null   int16
 8   has_hospital_or_clinic  2911 non-null   int16
 9   has_police_stn          2911 non-null   int16
 10  has_fire_stn            2911 non-null   int16
 11  has_mall                2911 non-null   int16
 12  has_market              2911 non-null   int16
 13  has_park                2911 non-null   int16
 14  has_bank_or_atm         2911 non-null   int16
 15  has_institute           2911 non-null   int16
 16  has_airport             2911 non-null   int16
 17  has_rly_stn             2911 non-null   int16
 18  has_metro_stn           2911 non-null   int16
 19  has_expy                2911 non-null   int16
 20  has_petrol_pump         2911 non-null   int16
 21  has_hotel               2911 non-null   int16
 22  has_temple_or_church    2911 non-null   int16
 23  has_famous_chowk        2911 non-null   int16
 24  has_club                2911 non-null   int16
 25  has_stadium             2911 non-null   int16
 26  has_restro_cafe         2911 non-null   int16
 27  fan                     2911 non-null   int16
 28  light                   2911 non-null   int16
 29  wardrobe                2911 non-null   int16
 30  ac                      2911 non-null   int16
 31  bed                     2911 non-null   int16
 32  chimney                 2911 non-null   int16
 33  curtains                2911 non-null   int16
 34  dining table            2911 non-null   int16
 35  exhaust fan             2911 non-null   int16
 36  geyser                  2911 non-null   int16
 37  modular kitchen         2911 non-null   int16
 38  microwave               2911 non-null   int16
 39  fridge                  2911 non-null   int16
 40  sofa                    2911 non-null   int16
 41  stove                   2911 non-null   int16
 42  tv                      2911 non-null   int16
 43  washing machine         2911 non-null   int16
 44  water purifier          2911 non-null   int16
 45  area_type               2911 non-null   object
 46  floor_rise              2911 non-null   object
 47  age                     2911 non-null   object
 48  society                 2911 non-null   object
 49  city                    2911 non-null   object
dtypes: float64(2), int16(43), object(5)
memory usage: 403.8+ KB

In [38]:
df.dropna()

,price_cr,area_sqm,bhk,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,area_type,floor_rise,age,society,city
0,0.45,83.61,2,2,1,0,7,50,34,0,0,0,0,0,5,2,0,0,0,0,0,0,1,0,0,0,1,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,carpet,mid,new,maa bhagwati residency,gurgaon
1,0.50,60.39,2,2,1,0,3,48,4,0,0,0,0,0,1,0,0,0,0,0,0,0,2,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,carpet,low,old,apna enclave,gurgaon
2,0.40,55.28,2,2,3,0,33,6,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,carpet,high,new,tulsiani easy in homes,sohna
3,1.47,111.48,2,2,2,1,61,9,1,0,0,1,0,0,0,2,1,1,1,0,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,carpet,low,mid aged,smart world orchard,gurgaon
4,0.70,124.95,2,2,3,1,92,11,4,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,1,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,super built up,mid,under construction,parkwood westend,gurgaon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2906,1.35,103.03,2,2,2,0,28,45,5,0,0,0,1,0,8,1,0,0,3,0,1,0,2,0,0,0,4,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,built up,low,old,dlf regency park 1,gurgaon
2907,1.05,176.05,3,3,3,1,86,4,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,super built up,high,under construction,ansal heights 86,gurgaon
2908,3.30,362.79,5,5,3,1,48,45,12,0,0,0,2,3,11,0,0,0,0,0,1,0,1,0,1,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,super built up,mid,old,parsvnath green ville,gurgaon
2909,5.80,343.74,3,4,3,1,24,42,4,0,0,0,0,0,8,0,0,0,4,0,0,0,1,0,0,0,2,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,built up,high,old,ambience lagoon,gurgaon
2910,11.00,290.14,4,6,3,1,54,13,0,0,0,1,0,0,0,3,0,0,1,0,0,0,0,0,0,0,0,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,super built up,mid,new,dlf the crest,gurgaon

In [39]:
df.to_csv('05_flats_FeatureEngineered.csv', index=False)