In [184]:
import numpy as np
import pandas as pd
import re
pd.set_option('display.max_columns', None)

import warnings as wr
wr.filterwarnings('ignore')

In [185]:
df = pd.read_csv('03_flats_cleaned.csv')

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bhk             2911 non-null   int64
 2   bathroom        2911 non-null   int64
 3   balcony         2911 non-null   int64
 4   addl_room       2911 non-null   int64
 5   floor_rise      2911 non-null   object
 6   area_sqm        2911 non-null   float64
 7   area_type       2911 non-null   object
 8   age             2911 non-null   object
 9   society         2911 non-null   object
 10  locality        2911 non-null   object
 11  furnishDetails  2150 non-null   object
 12  nearby_loc      2911 non-null   object
dtypes: float64(2), int64(4), object(7)
memory usage: 295.8+ KB

In [187]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,locality,furnishDetails,nearby_loc
2895,1.50,3,4,3,1,high,219.07000,super built up,new,corona optus,sector 37c gurgaon,"['3 wardrobe', '7 fan', '3 geyser', '15 light'...","['the esplanade mall', 'gurugram road', 'delhi..."
2297,0.74,2,2,3,0,high,114.27000,carpet,new,ashiana mulberry,sohna,"['1 modular kitchen', 'no ac', 'no bed', 'no c...","['discount department store', 'badshahpur sohn..."
2536,2.65,3,3,3,0,high,83.61204,carpet,new,godrej oasis,sector 88a gurgaon,"['1 exhaust fan', '1 stove', '1 light', '1 ac'...","['double infinity market', 'pataudi road', 'dw..."
1406,1.32,3,3,3,1,mid,157.47000,super built up,new,indiabulls centrum park,sector 103 gurgaon,"['5 ac', 'no bed', 'no chimney', 'no curtains'...","['gurgaon dreamz mall', 'huda market, sector 1..."

In [188]:
df['locality'].unique()

array(['krishna colony', 'ashok vihar', 'sohna', 'sector 61 gurgaon',
       'sector 92 gurgaon', 'dwarka expressway gurgaon',
       'sector 104 gurgaon', 'sector 88b gurgaon', 'sector 78 gurgaon',
       'sector 81 gurgaon', 'sector 79 gurgaon', 'sector 90 gurgaon',
       'sector 108 gurgaon', 'sector 62 gurgaon', 'sector 102 gurgaon',
       'sector-33 sohna', 'sector 89 gurgaon', 'sector 113 gurgaon',
       'sector 1 gurgaon', 'sector 65 gurgaon', 'sector 48 gurgaon',
       'sector 37c gurgaon', 'sector 3 gurgaon', 'new palam vihar',
       'sector 43 gurgaon', 'sector 88a gurgaon', 'sector 68 gurgaon',
       'sector 109 gurgaon', 'sector 106 gurgaon', 'sector 82 gurgaon',
       'ashok vihar phase 3 extension', 'sector 85 gurgaon',
       'sector 82a gurgaon', 'dlf phase 4', 'sector 10a gurgaon',
       'sector 1a imt manesar', 'block a surya vihar',
       'sector 84 gurgaon', 'sector 33 gurgaon', 'sector 71 gurgaon',
       'sector-7 housing board', 'sector 77 gurgaon',
       'sector 37d gurgaon', 'sector 67a gurgaon', 'sector 57 gurgaon',
       'sector 95 gurgaon', 'sector 99a gurgaon', 'sector 103 gurgaon',
       'sector 49 gurgaon', 'sector 30 gurgaon', 'sector 86 gurgaon',
       'sector 66 gurgaon', 'sector 15 part 1', 'laxman vihar',
       'sector 22 gurgaon', 'sector 63a gurgaon', 'sector 95a gurgaon',
       'sector 52 gurgaon', 'sector 67 gurgaon', 'sushant lok phase 1',
       'sector 107 gurgaon', 'sector 12a gurgaon', 'sohna road',
       'ashok vihar phase 2', 'rajiv colony', 'garauli kalan',
       'bhawani enclave', 'sector 99 gurgaon', 'iffco chowk',
       'palam vihar', 'sector 91 gurgaon', 'near sector 1 market',
       'sector 70 gurgaon', 'sector 70a gurgaon', 'gwal pahari',
       'sector 7 gurgaon', 'malibu town', 'golf course road',
       'sector 4 gurgaon', 'sector 54 gurgaon', 'sector 111 gurgaon',
       'chakkarpur', 'sector 41 gurgaon', 'sector 12 gurgaon',
       'sector 73 gurgaon', 'sector 36 sohna', 'sector 56 gurgaon',
       'sector 83 gurgaon', 'sector 53 gurgaon', 'sector 72 gurgaon',
       'sector 1 imt manesar', 'sector 69 gurgaon', 'sector 47 gurgaon',
       'sector 63 gurgaon', 'sector 110 gurgaon', 'kanahi', 'dlf phase 5',
       'sector 9a gurgaon', 'sector 28 gurgaon', 'sector 14 gurgaon',
       'nirvana country', 'dlf phase 2', 'sector 59 gurgaon',
       'dlf phase 3', 'heritage city', 'sector 38 gurgaon',
       'sector 15 gurgaon', 'ambience island', 'sector 112 gurgaon',
       'sector 45 gurgaon', 'sector 74 gurgaon', 'sector 60 gurgaon',
       'sector 2 gurgaon', 'sector 51 gurgaon', 'sector 50 gurgaon',
       'suncity', 'sector 110 a gurgaon', 'sector 39 gurgaon', 'sai kunj',
       'manesar', 'sector 58 gurgaon', 'imt manesar', 'sector 80 gurgaon',
       'mg road', 'sector 55 gurgaon', 'sultanpur', 'sector 93 gurgaon',
       'sector 23a gurgaon', 'sector 36a gurgaon', 'civil lines',
       'sector 76 gurgaon', 'new colony, sector 7', 'sector 31 gurgaon',
       'lajpat nagar', 'sector 89 a gurgaon', 'new gurgaon',
       'surya vihar', 'near pataudi chowk', 'cyber city', 'new colony',
       'subhash nagar', 'ats marigold', 'sector-2 sohna', 'adarsh nagar',
       'sector 37a gurgaon', 'sushant lok phase 3', 'carterpuri village',
       'valley view estate', 'shanti nagar', 'sushant lok',
       'mehrauli gurgaon road', 'laxman vihar phase 2',
       'gurgaon faridabad road', 'sector 36 gurgaon',
       'old delhi road, opp sector-14', 'sector 21 gurgaon',
       'sector 5 gurgaon', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'sector 24 gurgaon',
       'palam vihar extension', 'saroop garden rajendra park',
       'sector 4 urban estate', 'bptp', 'sector 105 gurgaon',
       'south city 1', 'sector 9 gurgaon', 'sector 40 gurgaon',
       'dharam colony', 'rajendra park',
       'godrej aria , sector 79 , gurgaon'], dtype=object)

In [189]:
df['city'] = np.where(df['locality'].str.contains('imt|manesar'), 'manesar',
                     np.where(df['locality'].str.contains('sohna'), 'sohna', 'gurgaon'))

In [190]:
df['city'].unique()

array(['gurgaon', 'sohna', 'manesar'], dtype=object)

In [191]:
#localities with sector not mentioned

In [192]:
df[~df['locality'].str.contains('sector')]['locality'].unique()

array(['krishna colony', 'ashok vihar', 'sohna',
       'dwarka expressway gurgaon', 'new palam vihar',
       'ashok vihar phase 3 extension', 'dlf phase 4',
       'block a surya vihar', 'laxman vihar', 'sushant lok phase 1',
       'sohna road', 'ashok vihar phase 2', 'rajiv colony',
       'garauli kalan', 'bhawani enclave', 'iffco chowk', 'palam vihar',
       'gwal pahari', 'malibu town', 'golf course road', 'chakkarpur',
       'kanahi', 'dlf phase 5', 'nirvana country', 'dlf phase 2',
       'dlf phase 3', 'heritage city', 'ambience island', 'suncity',
       'sai kunj', 'manesar', 'imt manesar', 'mg road', 'sultanpur',
       'civil lines', 'lajpat nagar', 'new gurgaon', 'surya vihar',
       'near pataudi chowk', 'cyber city', 'new colony', 'subhash nagar',
       'ats marigold', 'adarsh nagar', 'sushant lok phase 3',
       'carterpuri village', 'valley view estate', 'shanti nagar',
       'sushant lok', 'mehrauli gurgaon road', 'laxman vihar phase 2',
       'gurgaon faridabad road', 'dayanand colony', 'samaspur',
       'nirvana country pocket h', 'patel nagar', 'surat nagar 1',
       'sispal vihar', 'golf course ext road', 'shankar vihar',
       'new palam vihar phase 2', 'palam vihar extension',
       'saroop garden rajendra park', 'bptp', 'south city 1',
       'dharam colony', 'rajendra park'], dtype=object)

In [193]:
#changing these localities to their respective sectors

In [194]:
df['locality'] = df['locality'].str.replace('krishna colony','sector 7')
df['locality'] = df['locality'].str.replace('ashok vihar','sector 3')
df['locality'] = df['locality'].str.replace('sohna','sector 33')
df['locality'] = df['locality'].str.replace('dwarka expressway gurgaon','sector 102')
df['locality'] = df['locality'].str.replace('new palam vihar','sector 110')
df['locality'] = df['locality'].str.replace('ashok vihar phase 3 extension','sector 3')
df['locality'] = df['locality'].str.replace('dlf phase 4','sector 28')
df['locality'] = df['locality'].str.replace('block a surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('laxman vihar','sector 4')
df['locality'] = df['locality'].str.replace('sushant lok phase 1','sector 43')
df['locality'] = df['locality'].str.replace('sohna road','sector 48')
df['locality'] = df['locality'].str.replace('ashok vihar phase 2','sector 5')

In [195]:
df['locality'] = df['locality'].str.replace('rajiv colony','sector 33')
df['locality'] = df['locality'].str.replace('garauli kalan','sector 37')
df['locality'] = df['locality'].str.replace('bhawani enclave','sector 9')
df['locality'] = df['locality'].str.replace('iffco chowk','sector 17')
df['locality'] = df['locality'].str.replace('palam vihar','sector 2')
df['locality'] = df['locality'].str.replace('gwal pahari','sector 2')
df['locality'] = df['locality'].str.replace('malibu town','sector 47')
df['locality'] = df['locality'].str.replace('golf course road','sector 54')
df['locality'] = df['locality'].str.replace('chakkarpur','sector 28')
df['locality'] = df['locality'].str.replace('kanahi','sector 45')
df['locality'] = df['locality'].str.replace('dlf phase 5','sector 54')
df['locality'] = df['locality'].str.replace('nirvana country','sector 50')

In [196]:
df['locality'] = df['locality'].str.replace('dlf phase 2','sector 25')
df['locality'] = df['locality'].str.replace('dlf phase 3','sector 24')
df['locality'] = df['locality'].str.replace('heritage city','sector 25')
df['locality'] = df['locality'].str.replace('ambience island','sector 24')
df['locality'] = df['locality'].str.replace('suncity','sector 54')
df['locality'] = df['locality'].str.replace('sai kunj','sector 110')
df['locality'] = df['locality'].str.replace('manesar','sector 1')
df['locality'] = df['locality'].str.replace('imt manesar','sector 1')
df['locality'] = df['locality'].str.replace('mg road','sector 28')
df['locality'] = df['locality'].str.replace('sultanpur','sector 142')
df['locality'] = df['locality'].str.replace('civil lines','sector 15')
df['locality'] = df['locality'].str.replace('lajpat nagar','sector 4')

In [197]:
df['locality'] = df['locality'].str.replace('new gurgaon','sector 82')
df['locality'] = df['locality'].str.replace('surya vihar','sector 21')
df['locality'] = df['locality'].str.replace('near pataudi chowk','sector 10')
df['locality'] = df['locality'].str.replace('cyber city','sector 24')
df['locality'] = df['locality'].str.replace('new colony','sector 7')
df['locality'] = df['locality'].str.replace('subhash nagar','sector 8')
df['locality'] = df['locality'].str.replace('ats marigold','sector 89')
df['locality'] = df['locality'].str.replace('adarsh nagar','sector 12')
df['locality'] = df['locality'].str.replace('sushant lok phase 3','sector 57')
df['locality'] = df['locality'].str.replace('carterpuri village','sector 23')
df['locality'] = df['locality'].str.replace('valley view estate','sector 2')
df['locality'] = df['locality'].str.replace('shanti nagar','sector 11')

In [198]:
df['locality'] = df['locality'].str.replace('sushant lok','sector 43')
df['locality'] = df['locality'].str.replace('mehrauli gurgaon road','sector 28')
df['locality'] = df['locality'].str.replace('laxman vihar phase 2','sector 4')
df['locality'] = df['locality'].str.replace('gurgaon faridabad road','sector 56')
df['locality'] = df['locality'].str.replace('dayanand colony','sector 6')
df['locality'] = df['locality'].str.replace('samaspur','sector 51')
df['locality'] = df['locality'].str.replace('nirvana country pocket h','sector 50')
df['locality'] = df['locality'].str.replace('patel nagar','sector 15')
df['locality'] = df['locality'].str.replace('surat nagar 1','sector 104')
df['locality'] = df['locality'].str.replace('sispal vihar','sector 49')
df['locality'] = df['locality'].str.replace('golf course ext road','sector 65')
df['locality'] = df['locality'].str.replace('shankar vihar','sector 104')

In [199]:
df['locality'] = df['locality'].str.replace('new palam vihar phase 2','sector 110')
df['locality'] = df['locality'].str.replace('palam vihar extension','sector 2')
df['locality'] = df['locality'].str.replace('saroop garden rajendra park','sector 105')
df['locality'] = df['locality'].str.replace('bptp','sector 37')
df['locality'] = df['locality'].str.replace('south city 1','sector 41')
df['locality'] = df['locality'].str.replace('dharam colony','sector 23')
df['locality'] = df['locality'].str.replace('rajendra park','sector 105')

In [200]:
df[~df['locality'].str.contains('sector')]['locality'].unique()

array([], dtype=object)

In [201]:
df['sector'] = df['locality'].str.extract(r"(\d+)").astype('int16')

In [202]:
df['sector'].unique()

array([  7,   3,  33,  61,  92, 102, 104,  88,  78,  81,  79,  90, 108,
        62,  89, 113,   1,  65,  48,  37, 110,  43,  68, 109, 106,  82,
        85,  28,  10,  21,  84,  71,  77,  67,  57,  95,  99, 103,  49,
        30,  86,  66,  15,   4,  22,  63,  52, 107,  12,   9,  17,   2,
        91,  70,  47,  54, 111,  41,  73,  36,  56,  83,  53,  72,  69,
        45,  14,  50,  25,  59,  24,  38, 112,  74,  60,  51,  39,  58,
        80,  55, 142,  93,  23,  76,  31,   8,  11,   5,   6, 105,  40],
      dtype=int16)

In [203]:
df['locality'].unique()

array(['sector 7', 'sector 3', 'sector 33', 'sector 61 gurgaon',
       'sector 92 gurgaon', 'sector 102', 'sector 104 gurgaon',
       'sector 88b gurgaon', 'sector 78 gurgaon', 'sector 81 gurgaon',
       'sector 79 gurgaon', 'sector 90 gurgaon', 'sector 108 gurgaon',
       'sector 62 gurgaon', 'sector 102 gurgaon', 'sector-33 sector 33',
       'sector 89 gurgaon', 'sector 113 gurgaon', 'sector 1 gurgaon',
       'sector 65 gurgaon', 'sector 48 gurgaon', 'sector 37c gurgaon',
       'sector 3 gurgaon', 'sector 110', 'sector 43 gurgaon',
       'sector 88a gurgaon', 'sector 68 gurgaon', 'sector 109 gurgaon',
       'sector 106 gurgaon', 'sector 82 gurgaon',
       'sector 3 phase 3 extension', 'sector 85 gurgaon',
       'sector 82a gurgaon', 'sector 28', 'sector 10a gurgaon',
       'sector 1a imt sector 1', 'sector 21', 'sector 84 gurgaon',
       'sector 33 gurgaon', 'sector 71 gurgaon', 'sector-7 housing board',
       'sector 77 gurgaon', 'sector 37d gurgaon', 'sector 67a gurgaon',
       'sector 57 gurgaon', 'sector 95 gurgaon', 'sector 99a gurgaon',
       'sector 103 gurgaon', 'sector 49 gurgaon', 'sector 30 gurgaon',
       'sector 86 gurgaon', 'sector 66 gurgaon', 'sector 15 part 1',
       'sector 4', 'sector 22 gurgaon', 'sector 63a gurgaon',
       'sector 95a gurgaon', 'sector 52 gurgaon', 'sector 67 gurgaon',
       'sector 43', 'sector 107 gurgaon', 'sector 12a gurgaon',
       'sector 33 road', 'sector 3 phase 2', 'sector 37', 'sector 9',
       'sector 99 gurgaon', 'sector 17', 'sector 2', 'sector 91 gurgaon',
       'near sector 1 market', 'sector 70 gurgaon', 'sector 70a gurgaon',
       'sector 7 gurgaon', 'sector 47', 'sector 54', 'sector 4 gurgaon',
       'sector 54 gurgaon', 'sector 111 gurgaon', 'sector 41 gurgaon',
       'sector 12 gurgaon', 'sector 73 gurgaon', 'sector 36 sector 33',
       'sector 56 gurgaon', 'sector 83 gurgaon', 'sector 53 gurgaon',
       'sector 72 gurgaon', 'sector 1 imt sector 1', 'sector 69 gurgaon',
       'sector 47 gurgaon', 'sector 63 gurgaon', 'sector 110 gurgaon',
       'sector 45', 'sector 9a gurgaon', 'sector 28 gurgaon',
       'sector 14 gurgaon', 'sector 50', 'sector 25', 'sector 59 gurgaon',
       'sector 24', 'sector 38 gurgaon', 'sector 15 gurgaon',
       'sector 112 gurgaon', 'sector 45 gurgaon', 'sector 74 gurgaon',
       'sector 60 gurgaon', 'sector 2 gurgaon', 'sector 51 gurgaon',
       'sector 50 gurgaon', 'sector 110 a gurgaon', 'sector 39 gurgaon',
       'sector 1', 'sector 58 gurgaon', 'imt sector 1',
       'sector 80 gurgaon', 'sector 55 gurgaon', 'sector 142',
       'sector 93 gurgaon', 'sector 23a gurgaon', 'sector 36a gurgaon',
       'sector 15', 'sector 76 gurgaon', 'sector 7, sector 7',
       'sector 31 gurgaon', 'sector 89 a gurgaon', 'sector 82',
       'sector 10', 'sector 8', 'sector 89', 'sector-2 sector 33',
       'sector 12', 'sector 37a gurgaon', 'sector 57', 'sector 23',
       'sector 11', 'sector 4 phase 2', 'sector 56', 'sector 36 gurgaon',
       'old delhi road, opp sector-14', 'sector 21 gurgaon',
       'sector 5 gurgaon', 'sector 6', 'sector 51', 'sector 50 pocket h',
       'sector 104', 'sector 49', 'sector 65', 'sector 110 phase 2',
       'sector 24 gurgaon', 'sector 2 extension', 'sector 105',
       'sector 4 urban estate', 'sector 105 gurgaon', 'sector 41',
       'sector 9 gurgaon', 'sector 40 gurgaon',
       'godrej aria , sector 79 , gurgaon'], dtype=object)

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bhk             2911 non-null   int64
 2   bathroom        2911 non-null   int64
 3   balcony         2911 non-null   int64
 4   addl_room       2911 non-null   int64
 5   floor_rise      2911 non-null   object
 6   area_sqm        2911 non-null   float64
 7   area_type       2911 non-null   object
 8   age             2911 non-null   object
 9   society         2911 non-null   object
 10  locality        2911 non-null   object
 11  furnishDetails  2150 non-null   object
 12  nearby_loc      2911 non-null   object
 13  city            2911 non-null   object
 14  sector          2911 non-null   int16
dtypes: float64(2), int16(1), int64(4), object(8)
memory usage: 324.2+ KB

In [205]:
df.drop(columns=['locality'], inplace=True)

In [206]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2911 entries, 0 to 2910
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   price_cr        2904 non-null   float64
 1   bhk             2911 non-null   int64
 2   bathroom        2911 non-null   int64
 3   balcony         2911 non-null   int64
 4   addl_room       2911 non-null   int64
 5   floor_rise      2911 non-null   object
 6   area_sqm        2911 non-null   float64
 7   area_type       2911 non-null   object
 8   age             2911 non-null   object
 9   society         2911 non-null   object
 10  furnishDetails  2150 non-null   object
 11  nearby_loc      2911 non-null   object
 12  city            2911 non-null   object
 13  sector          2911 non-null   int16
dtypes: float64(2), int16(1), int64(4), object(7)
memory usage: 301.5+ KB

In [207]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,furnishDetails,nearby_loc,city,sector
2513,1.50,3,3,1,1,mid,210.61,carpet,new,brisk lumbini terrace homes,"['1 modular kitchen', 'no ac', 'no bed', 'no c...","['palam vihar vyapar kendra', 'ram mandir', 'k...",gurgaon,109
559,1.32,2,2,3,1,high,140.00,super built up,new,m3m the marina,"['3 ac', '1 chimney', '1 modular kitchen', 'no...","['airia mall', 'southern peripheral road', 'so...",gurgaon,68
1973,5.00,3,4,3,0,high,399.48,carpet,old,central park 2 bellevue,"['3 wardrobe', '1 modular kitchen', 'no ac', '...","['rajiv chowk mosque', 'icici bank atm', 'stan...",gurgaon,48
1281,1.40,3,4,2,1,mid,210.15,super built up,old,godrej frontier,NaN,"['pooja clinic', 'dr. sahil clinic', 'prakash ...",gurgaon,80

In [208]:
# handling nearby_loc feature
import ast

df['nearby_1'] = df['nearby_loc'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

df['landmark_count'] = df['nearby_1'].apply(lambda x: len(x))

In [209]:
from collections import Counter

stopwords = {'the', 'a', 'an', 'and', 'of', 'in', 'at', 'to', 'is', 'for', 'on'}

all_words = []
for landmark_list in df['nearby_1']:
    for landmark in landmark_list:
        # Lowercase, remove special characters, split into words
        words = re.sub(r'[^a-z0-9\s]', '', landmark.lower()).split()
        # Filter stopwords and short tokens
        filtered = [w for w in words if w not in stopwords and len(w) > 2]
        all_words.extend(filtered)

word_freq = Counter(all_words)

In [210]:
top_n = 100
nearby_freq = pd.DataFrame(word_freq.most_common(top_n), columns=['word', 'frequency'])

In [211]:
not_landmark = ('gurgaon','sector','gandhi','indira','dwarka','gurugram','sohna',
                'igi','delhi','manesar','imt','5556','sec')

general_landmarks = nearby_freq[~nearby_freq['word'].isin(not_landmark)].iloc[:,0].tolist()

In [212]:
#def famous_landmarks_only(row):
#    row = row.replace('[','').replace(']','').replace("'","").replace("\\","").split(",")
#    famous_landmarks = []
#    for item in row:
#        for general_landmark in general_landmarks:
#            if general_landmark in item:
#                famous_landmarks.append(item)
#    return famous_landmarks
#
#df['landmarks'] = df['nearby_loc'].apply(famous_landmarks_only)

In [216]:
landmark_dict = {
    'has_hospital_or_clinic': ['hospital','nursing','clinic','health care'],
    'has_police_stn': ['police'],
    'has_fire_stn': ['fire'],
    'has_mall': ['mall'],
    'has_market': ['pharmacy','market'],
    'has_park': ['park'],
    'has_bank_or_atm': ['bank','atm'],
    'has_institute': ['school','institute','college','university','academy'],
    'has_airport': ['airport'],
    'has_rly_stn': ['railway','rly'],
    'has_metro_stn': ['metro'],
    'has_expy': ['expressway','expy'],
    'has_fuel_stn': ['petrol','cng'],
    'has_hotel': ['hotel','inn','radisson','lemontree'],
    'has_temple': ['temple','mandir'],
    'has_famous_chowk': ['chowk'],
    'has_club': ['club'],
    'has_stadium': ['stadium'],
    'has_restro_cafe': ['restaurant','cafe','food court']
}

In [ ]:
def landmark_clean(landmarks_list):
    for landmark in landmarks_list:
        for key, value in landmark_dict.items():
            for value

In [215]:
df['has_hospital'] = df['nearby_loc'].apply(lambda x: [1 for ])

AttributeError: 'str' object has no attribute 'isin'

In [183]:
general_landmarks

['hospital',
 'bank',
 'school',
 'station',
 'park',
 'international',
 'airport',
 'mall',
 'clinic',
 'road',
 'atm',
 'metro',
 'centre',
 'university',
 'expressway',
 'golf',
 'hdfc',
 'dental',
 'railway',
 'course',
 'public',
 'institute',
 'petrol',
 'pump',
 'inn',
 'trampoline',
 'skyjumper',
 'icici',
 'mandir',
 'dpg',
 'hotel',
 'huda',
 'business',
 'india',
 'care',
 'technology',
 'intl',
 'garhi',
 'city',
 'state',
 'holiday',
 'chowk',
 'harsaru',
 'sapphire',
 'axis',
 'central',
 'market',
 'maternity',
 'expy',
 'academy',
 'college',
 'peripheral',
 'home',
 'junction',
 'radisson',
 'eye',
 'dlf',
 'apollo',
 'club',
 'airia',
 'indian',
 'euro',
 'northcap',
 'nursing',
 'indusind',
 'shri',
 'oil',
 'vihar',
 'stadium',
 'pharmacy',
 'national',
 'vatika',
 'country',
 'basai',
 'extension',
 'trauma',
 'palam',
 'global',
 'hospitals',
 'krishna',
 'health',
 'aarvy',
 'cafe',
 'pizza',
 'genesis',
 'hyatt',
 'sgt']

In [ ]:
df.drop(columns=['nearby_1','nearby_loc'], inplace=True)

In [180]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

def embed_landmarks(landmark_list):
    embeddings = model.encode(landmark_list)       # shape: (n_landmarks, 384)
    return np.mean(embeddings, axis=0)             # mean pooling → (384,)

landmark_vecs = np.vstack(df['landmarks'].apply(embed_landmarks))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [182]:
landmark_vecs.shape

(2911, 384)

In [29]:
for row in df['furnishDetails']:
    row = str(row).replace('[','').replace(']','').replace("'","").replace('no','0').strip().split(",")
    for item in row:
        if item != 'nan':
            name_obj = re.findall(r"([a-zA-Z/s]+)", item)
            if name_obj is not None:
                name = " ".join(name_obj)
                
            count_obj = re.search(r"(\d+)", item)
            if count_obj is not None:
                count = count_obj.group()
                df[name]=count

df.drop(columns=['furnishDetails'], inplace=True)

In [30]:
df.sample(4)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,society,city,sector,landmarks,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier
172,2.15,3,5,3,0,low,223.71,super built up,new,ss the leaf,gurgaon,85,"[sapphire 83 mall, dwarka expressway, delhi ...",6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
1438,1.90,3,4,2,1,high,178.37,super built up,new,emaar mgf the enclave,gurgaon,66,"[ elan empire mall, airia mall]",6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
355,2.60,3,3,3,1,low,241.36,super built up,new,adani m2k oyster grande,gurgaon,102,"[wtc plaza, star mall, dwarka expy, prime s...",6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0
1630,1.15,3,3,3,1,high,168.90,super built up,new,dlf regal gardens,gurgaon,90,[ imt manesar],6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0

In [31]:
df.columns

Index(['price_cr', 'bhk', 'bathroom', 'balcony', 'addl_room', 'floor_rise',
       'area_sqm', 'area_type', 'age', 'society', 'city', 'sector',
       'landmarks', 'fan', 'light', 'wardrobe', 'ac', 'bed', 'chimney',
       'curtains', 'dining table', 'exhaust fan', 'geyser', 'modular kitchen',
       'microwave', 'fridge', 'sofa', 'stove', 'tv', 'washing machine',
       'water purifier'],
      dtype='object')

In [32]:
df = df.reindex(columns=['price_cr', 'bhk', 'bathroom', 'balcony', 'addl_room', 'floor_rise',
       'area_sqm', 'area_type', 'age', 'fan', 'light', 'wardrobe', 'ac', 'bed', 'chimney',
       'curtains', 'dining table', 'exhaust fan', 'geyser', 'modular kitchen',
       'microwave', 'fridge', 'sofa', 'stove', 'tv', 'washing machine',
       'water purifier', 'society', 'sector', 'city', 'landmarks'])

In [33]:
df.sample(3)

,price_cr,bhk,bathroom,balcony,addl_room,floor_rise,area_sqm,area_type,age,fan,light,wardrobe,ac,bed,chimney,curtains,dining table,exhaust fan,geyser,modular kitchen,microwave,fridge,sofa,stove,tv,washing machine,water purifier,society,sector,city,landmarks
1245,1.05,2,2,3,0,high,152.36,super built up,new,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,ss the leaf,85,gurgaon,"[sapphire 83 mall, dwarka expressway, delhi ..."
1161,0.89,2,2,3,1,high,130.44,super built up,new,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,tarc maceo,91,gurgaon,"[ dwarka expressway, rao bharat singh interna..."
2429,0.38,2,2,2,0,low,60.39,super built up,new,6,10,4,6,0,1,0,0,1,5,1,1,1,0,1,0,1,0,signature global solera,107,gurgaon,"[gurgaon dreamz mall, dwarka expressway, s c..."

In [35]:
df.to_csv('05_flats_FeatureEngineered.csv', index=False)